/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface IDividendsInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "claimDividend"
      | "claimedBalanceAt"
      | "fundDividend"
      | "fundsAt"
      | "tokensAt"
      | "totalAwardedBalanceAt"
      | "unclaimedBalanceAt"
      | "withdrawalRemains"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "Claimed" | "Funded" | "Withdrawn"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "claimDividend",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimedBalanceAt",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "fundDividend",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "fundsAt",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "tokensAt",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "totalAwardedBalanceAt",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "unclaimedBalanceAt",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawalRemains",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "claimDividend",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimedBalanceAt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fundDividend",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "fundsAt", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "tokensAt", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalAwardedBalanceAt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unclaimedBalanceAt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawalRemains",
    data: BytesLike
  ): Result;
}

export namespace ClaimedEvent {
  export type InputTuple = [
    payee: AddressLike,
    token: AddressLike,
    amount: BigNumberish,
    snapshotId: BigNumberish
  ];
  export type OutputTuple = [
    payee: string,
    token: string,
    amount: bigint,
    snapshotId: bigint
  ];
  export interface OutputObject {
    payee: string;
    token: string;
    amount: bigint;
    snapshotId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FundedEvent {
  export type InputTuple = [
    payer: AddressLike,
    token: AddressLike,
    amount: BigNumberish,
    snapshotId: BigNumberish
  ];
  export type OutputTuple = [
    payer: string,
    token: string,
    amount: bigint,
    snapshotId: bigint
  ];
  export interface OutputObject {
    payer: string;
    token: string;
    amount: bigint;
    snapshotId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawnEvent {
  export type InputTuple = [
    payee: AddressLike,
    token: AddressLike,
    amount: BigNumberish,
    snapshotId: BigNumberish
  ];
  export type OutputTuple = [
    payee: string,
    token: string,
    amount: bigint,
    snapshotId: bigint
  ];
  export interface OutputObject {
    payee: string;
    token: string;
    amount: bigint;
    snapshotId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IDividends extends BaseContract {
  connect(runner?: ContractRunner | null): IDividends;
  waitForDeployment(): Promise<this>;

  interface: IDividendsInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  claimDividend: TypedContractMethod<
    [token: AddressLike, snapshotId: BigNumberish],
    [void],
    "nonpayable"
  >;

  claimedBalanceAt: TypedContractMethod<
    [token: AddressLike, receiver: AddressLike, snapshotId: BigNumberish],
    [bigint],
    "view"
  >;

  fundDividend: TypedContractMethod<
    [token: AddressLike, amount: BigNumberish, snapshotId: BigNumberish],
    [void],
    "nonpayable"
  >;

  fundsAt: TypedContractMethod<
    [token: AddressLike, snapshotId: BigNumberish],
    [bigint],
    "view"
  >;

  tokensAt: TypedContractMethod<
    [token: AddressLike, snapshotId: BigNumberish],
    [bigint],
    "view"
  >;

  totalAwardedBalanceAt: TypedContractMethod<
    [token: AddressLike, receiver: AddressLike, snapshotId: BigNumberish],
    [bigint],
    "view"
  >;

  unclaimedBalanceAt: TypedContractMethod<
    [token: AddressLike, receiver: AddressLike, snapshotId: BigNumberish],
    [bigint],
    "view"
  >;

  withdrawalRemains: TypedContractMethod<
    [token: AddressLike, snapshotId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "claimDividend"
  ): TypedContractMethod<
    [token: AddressLike, snapshotId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "claimedBalanceAt"
  ): TypedContractMethod<
    [token: AddressLike, receiver: AddressLike, snapshotId: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "fundDividend"
  ): TypedContractMethod<
    [token: AddressLike, amount: BigNumberish, snapshotId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "fundsAt"
  ): TypedContractMethod<
    [token: AddressLike, snapshotId: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "tokensAt"
  ): TypedContractMethod<
    [token: AddressLike, snapshotId: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "totalAwardedBalanceAt"
  ): TypedContractMethod<
    [token: AddressLike, receiver: AddressLike, snapshotId: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "unclaimedBalanceAt"
  ): TypedContractMethod<
    [token: AddressLike, receiver: AddressLike, snapshotId: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "withdrawalRemains"
  ): TypedContractMethod<
    [token: AddressLike, snapshotId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "Claimed"
  ): TypedContractEvent<
    ClaimedEvent.InputTuple,
    ClaimedEvent.OutputTuple,
    ClaimedEvent.OutputObject
  >;
  getEvent(
    key: "Funded"
  ): TypedContractEvent<
    FundedEvent.InputTuple,
    FundedEvent.OutputTuple,
    FundedEvent.OutputObject
  >;
  getEvent(
    key: "Withdrawn"
  ): TypedContractEvent<
    WithdrawnEvent.InputTuple,
    WithdrawnEvent.OutputTuple,
    WithdrawnEvent.OutputObject
  >;

  filters: {
    "Claimed(address,address,uint256,uint256)": TypedContractEvent<
      ClaimedEvent.InputTuple,
      ClaimedEvent.OutputTuple,
      ClaimedEvent.OutputObject
    >;
    Claimed: TypedContractEvent<
      ClaimedEvent.InputTuple,
      ClaimedEvent.OutputTuple,
      ClaimedEvent.OutputObject
    >;

    "Funded(address,address,uint256,uint256)": TypedContractEvent<
      FundedEvent.InputTuple,
      FundedEvent.OutputTuple,
      FundedEvent.OutputObject
    >;
    Funded: TypedContractEvent<
      FundedEvent.InputTuple,
      FundedEvent.OutputTuple,
      FundedEvent.OutputObject
    >;

    "Withdrawn(address,address,uint256,uint256)": TypedContractEvent<
      WithdrawnEvent.InputTuple,
      WithdrawnEvent.OutputTuple,
      WithdrawnEvent.OutputObject
    >;
    Withdrawn: TypedContractEvent<
      WithdrawnEvent.InputTuple,
      WithdrawnEvent.OutputTuple,
      WithdrawnEvent.OutputObject
    >;
  };
}
