/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace AssetExchange {
  export type OrderStruct = {
    id: BigNumberish;
    maker: AddressLike;
    tokenSell: AddressLike;
    tokenBuy: AddressLike;
    amountSell: BigNumberish;
    amountBuy: BigNumberish;
    filledSell: BigNumberish;
    filledBuy: BigNumberish;
    cancelled: boolean;
  };

  export type OrderStructOutput = [
    id: bigint,
    maker: string,
    tokenSell: string,
    tokenBuy: string,
    amountSell: bigint,
    amountBuy: bigint,
    filledSell: bigint,
    filledBuy: bigint,
    cancelled: boolean
  ] & {
    id: bigint;
    maker: string;
    tokenSell: string;
    tokenBuy: string;
    amountSell: bigint;
    amountBuy: bigint;
    filledSell: bigint;
    filledBuy: bigint;
    cancelled: boolean;
  };
}

export interface AssetExchangeInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "cancelOrder"
      | "createOrder"
      | "fillOrder"
      | "getOrder"
      | "getOrders"
      | "nextOrderId"
      | "orders"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "OrderCancelled" | "OrderCreated" | "OrderFilled"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "cancelOrder",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createOrder",
    values: [AddressLike, AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "fillOrder",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getOrder",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getOrders",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "nextOrderId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "orders",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "cancelOrder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createOrder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "fillOrder", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getOrder", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getOrders", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "nextOrderId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "orders", data: BytesLike): Result;
}

export namespace OrderCancelledEvent {
  export type InputTuple = [orderId: BigNumberish, maker: AddressLike];
  export type OutputTuple = [orderId: bigint, maker: string];
  export interface OutputObject {
    orderId: bigint;
    maker: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OrderCreatedEvent {
  export type InputTuple = [
    orderId: BigNumberish,
    maker: AddressLike,
    tokenSell: AddressLike,
    tokenBuy: AddressLike,
    amountSell: BigNumberish,
    amountBuy: BigNumberish
  ];
  export type OutputTuple = [
    orderId: bigint,
    maker: string,
    tokenSell: string,
    tokenBuy: string,
    amountSell: bigint,
    amountBuy: bigint
  ];
  export interface OutputObject {
    orderId: bigint;
    maker: string;
    tokenSell: string;
    tokenBuy: string;
    amountSell: bigint;
    amountBuy: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OrderFilledEvent {
  export type InputTuple = [
    orderId: BigNumberish,
    taker: AddressLike,
    fillAmountSell: BigNumberish,
    fillAmountBuy: BigNumberish
  ];
  export type OutputTuple = [
    orderId: bigint,
    taker: string,
    fillAmountSell: bigint,
    fillAmountBuy: bigint
  ];
  export interface OutputObject {
    orderId: bigint;
    taker: string;
    fillAmountSell: bigint;
    fillAmountBuy: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AssetExchange extends BaseContract {
  connect(runner?: ContractRunner | null): AssetExchange;
  waitForDeployment(): Promise<this>;

  interface: AssetExchangeInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  cancelOrder: TypedContractMethod<
    [orderId: BigNumberish],
    [void],
    "nonpayable"
  >;

  createOrder: TypedContractMethod<
    [
      tokenSell: AddressLike,
      tokenBuy: AddressLike,
      amountSell: BigNumberish,
      amountBuy: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  fillOrder: TypedContractMethod<
    [orderId: BigNumberish, fillAmountBuy: BigNumberish],
    [void],
    "nonpayable"
  >;

  getOrder: TypedContractMethod<
    [orderId: BigNumberish],
    [AssetExchange.OrderStructOutput],
    "view"
  >;

  getOrders: TypedContractMethod<
    [tokenSell: AddressLike, tokenBuy: AddressLike],
    [AssetExchange.OrderStructOutput[]],
    "view"
  >;

  nextOrderId: TypedContractMethod<[], [bigint], "view">;

  orders: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean
      ] & {
        id: bigint;
        maker: string;
        tokenSell: string;
        tokenBuy: string;
        amountSell: bigint;
        amountBuy: bigint;
        filledSell: bigint;
        filledBuy: bigint;
        cancelled: boolean;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "cancelOrder"
  ): TypedContractMethod<[orderId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createOrder"
  ): TypedContractMethod<
    [
      tokenSell: AddressLike,
      tokenBuy: AddressLike,
      amountSell: BigNumberish,
      amountBuy: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "fillOrder"
  ): TypedContractMethod<
    [orderId: BigNumberish, fillAmountBuy: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getOrder"
  ): TypedContractMethod<
    [orderId: BigNumberish],
    [AssetExchange.OrderStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getOrders"
  ): TypedContractMethod<
    [tokenSell: AddressLike, tokenBuy: AddressLike],
    [AssetExchange.OrderStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "nextOrderId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "orders"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean
      ] & {
        id: bigint;
        maker: string;
        tokenSell: string;
        tokenBuy: string;
        amountSell: bigint;
        amountBuy: bigint;
        filledSell: bigint;
        filledBuy: bigint;
        cancelled: boolean;
      }
    ],
    "view"
  >;

  getEvent(
    key: "OrderCancelled"
  ): TypedContractEvent<
    OrderCancelledEvent.InputTuple,
    OrderCancelledEvent.OutputTuple,
    OrderCancelledEvent.OutputObject
  >;
  getEvent(
    key: "OrderCreated"
  ): TypedContractEvent<
    OrderCreatedEvent.InputTuple,
    OrderCreatedEvent.OutputTuple,
    OrderCreatedEvent.OutputObject
  >;
  getEvent(
    key: "OrderFilled"
  ): TypedContractEvent<
    OrderFilledEvent.InputTuple,
    OrderFilledEvent.OutputTuple,
    OrderFilledEvent.OutputObject
  >;

  filters: {
    "OrderCancelled(uint256,address)": TypedContractEvent<
      OrderCancelledEvent.InputTuple,
      OrderCancelledEvent.OutputTuple,
      OrderCancelledEvent.OutputObject
    >;
    OrderCancelled: TypedContractEvent<
      OrderCancelledEvent.InputTuple,
      OrderCancelledEvent.OutputTuple,
      OrderCancelledEvent.OutputObject
    >;

    "OrderCreated(uint256,address,address,address,uint256,uint256)": TypedContractEvent<
      OrderCreatedEvent.InputTuple,
      OrderCreatedEvent.OutputTuple,
      OrderCreatedEvent.OutputObject
    >;
    OrderCreated: TypedContractEvent<
      OrderCreatedEvent.InputTuple,
      OrderCreatedEvent.OutputTuple,
      OrderCreatedEvent.OutputObject
    >;

    "OrderFilled(uint256,address,uint256,uint256)": TypedContractEvent<
      OrderFilledEvent.InputTuple,
      OrderFilledEvent.OutputTuple,
      OrderFilledEvent.OutputObject
    >;
    OrderFilled: TypedContractEvent<
      OrderFilledEvent.InputTuple,
      OrderFilledEvent.OutputTuple,
      OrderFilledEvent.OutputObject
    >;
  };
}
