/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface WrappedAssetFactoryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "createWrappedAsset"
      | "getAssetAtIndex"
      | "getTotalAssets"
      | "getUserAssets"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "AssetCreated"): EventFragment;

  encodeFunctionData(
    functionFragment: "createWrappedAsset",
    values: [
      string,
      string,
      BytesLike,
      string,
      BigNumberish,
      BigNumberish,
      AddressLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getAssetAtIndex",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalAssets",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getUserAssets",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "createWrappedAsset",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAssetAtIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalAssets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserAssets",
    data: BytesLike
  ): Result;
}

export namespace AssetCreatedEvent {
  export type InputTuple = [
    creator: AddressLike,
    assetAddress: AddressLike,
    name: string,
    symbol: string,
    documentHash: BytesLike,
    documentType: string,
    originalValue: BigNumberish,
    mintAmount: BigNumberish,
    recipient: AddressLike
  ];
  export type OutputTuple = [
    creator: string,
    assetAddress: string,
    name: string,
    symbol: string,
    documentHash: string,
    documentType: string,
    originalValue: bigint,
    mintAmount: bigint,
    recipient: string
  ];
  export interface OutputObject {
    creator: string;
    assetAddress: string;
    name: string;
    symbol: string;
    documentHash: string;
    documentType: string;
    originalValue: bigint;
    mintAmount: bigint;
    recipient: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface WrappedAssetFactory extends BaseContract {
  connect(runner?: ContractRunner | null): WrappedAssetFactory;
  waitForDeployment(): Promise<this>;

  interface: WrappedAssetFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  createWrappedAsset: TypedContractMethod<
    [
      _name: string,
      _symbol: string,
      _documentHash: BytesLike,
      _documentType: string,
      _originalValue: BigNumberish,
      _mintAmount: BigNumberish,
      _recipient: AddressLike
    ],
    [string],
    "nonpayable"
  >;

  getAssetAtIndex: TypedContractMethod<[index: BigNumberish], [string], "view">;

  getTotalAssets: TypedContractMethod<[], [bigint], "view">;

  getUserAssets: TypedContractMethod<[user: AddressLike], [string[]], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "createWrappedAsset"
  ): TypedContractMethod<
    [
      _name: string,
      _symbol: string,
      _documentHash: BytesLike,
      _documentType: string,
      _originalValue: BigNumberish,
      _mintAmount: BigNumberish,
      _recipient: AddressLike
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getAssetAtIndex"
  ): TypedContractMethod<[index: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getTotalAssets"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getUserAssets"
  ): TypedContractMethod<[user: AddressLike], [string[]], "view">;

  getEvent(
    key: "AssetCreated"
  ): TypedContractEvent<
    AssetCreatedEvent.InputTuple,
    AssetCreatedEvent.OutputTuple,
    AssetCreatedEvent.OutputObject
  >;

  filters: {
    "AssetCreated(address,address,string,string,bytes32,string,uint256,uint256,address)": TypedContractEvent<
      AssetCreatedEvent.InputTuple,
      AssetCreatedEvent.OutputTuple,
      AssetCreatedEvent.OutputObject
    >;
    AssetCreated: TypedContractEvent<
      AssetCreatedEvent.InputTuple,
      AssetCreatedEvent.OutputTuple,
      AssetCreatedEvent.OutputObject
    >;
  };
}
