# -- Build stage ---------------------------------------------------------------
FROM node:22.11-slim AS build

WORKDIR /app

COPY package.json package-lock.json ./

# Install deps needed to build the frontend (skip hardhat/solc native scripts).
# Use `npm install` instead of `npm ci` to tolerate minor lockfile drift across
# npm versions; the build is hermetic inside Docker so reproducibility is safe.
# Retry once on transient network failures (ECONNRESET in Cloud Build).
RUN npm install --ignore-scripts || npm install --ignore-scripts

COPY . .

# Source ephemeral build env vars (if present) before running Vite.
# `vite.build.env` is generated by scripts/deploy-frontend-cloudrun.sh.
RUN set -a \
  && if [ -f ./vite.build.env ]; then . ./vite.build.env; fi \
  && set +a \
  && npx vite build

# -- Production stage: serve static files -------------------------------------
FROM node:22.11-slim

RUN apt-get update && apt-get install -y --no-install-recommends wget \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

RUN npm install -g serve

# Create non-root user
RUN addgroup --system --gid 1001 nodejs && \
    adduser --system --uid 1001 --ingroup nodejs appuser

COPY --from=build --chown=appuser:nodejs /app/dist ./dist
COPY --chown=appuser:nodejs config/serve.json ./config/serve.json

ENV NODE_ENV=production
ENV PORT=3000

EXPOSE 3000

HEALTHCHECK --interval=30s --timeout=3s --start-period=5s --retries=3 \
  CMD wget --no-verbose --tries=1 --spider http://localhost:3000/ || exit 1

USER appuser

CMD ["sh", "-c", "node -e \"const fs=require('fs');const entries=Object.entries(process.env).filter(([key,value])=>key.startsWith('VITE_')&&typeof value==='string'&&value.length>0);const runtimeEnv=Object.fromEntries(entries);fs.writeFileSync('/app/dist/runtime-env.js','window.__FUEKI_RUNTIME_ENV__='+JSON.stringify(runtimeEnv)+';\\\\n');\" && serve -s dist -c /app/config/serve.json -l tcp://0.0.0.0:${PORT:-3000}"]
