[variables]
NODE_ENV = "production"
NIXPACKS_NX_CACHE_DIR = "/tmp/.cache"

[phases.install]
cmds = ["npm ci --include=dev --ignore-scripts"]

[phases.build]
cmds = ["npm run build:railway"]

[start]
cmd = "npx vite preview"
