/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../common";
import type {
  SecurityTokenDeployer,
  SecurityTokenDeployerInterface,
} from "../../../contracts/security-token/SecurityTokenDeployer";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes",
        name: "bytecode",
        type: "bytes",
      },
    ],
    name: "deploy",
    outputs: [
      {
        internalType: "address",
        name: "addr",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

const _bytecode =
  "0x6080806040523461001657610151908161001c8239f35b600080fdfe6080604052600436101561001257600080fd5b6000803560e01c627743601461002757600080fd5b346100db5760203660031901126100db576001600160401b036004358181116100d757366023820112156100d7578060040135908282116100d25760405192601f8301601f19908116603f01168401908111848210176100d25760405281835236602483830101116100ce57926020826100b0949360246100ca970183860137830101526100f4565b6040516001600160a01b0390911681529081906020820190565b0390f35b8380fd5b6100de565b8280fd5b80fd5b634e487b7160e01b600052604160045260246000fd5b6020815191016000f0906001600160a01b0382161561010f57565b60405162461bcd60e51b815260206004820152600d60248201526c11195c1b1bde4819985a5b1959609a1b6044820152606490fdfea164736f6c6343000814000a";

type SecurityTokenDeployerConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: SecurityTokenDeployerConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class SecurityTokenDeployer__factory extends ContractFactory {
  constructor(...args: SecurityTokenDeployerConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      SecurityTokenDeployer & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(
    runner: ContractRunner | null
  ): SecurityTokenDeployer__factory {
    return super.connect(runner) as SecurityTokenDeployer__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): SecurityTokenDeployerInterface {
    return new Interface(_abi) as SecurityTokenDeployerInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): SecurityTokenDeployer {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as SecurityTokenDeployer;
  }
}
