/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../common";
import type {
  OrbitalMath,
  OrbitalMathInterface,
} from "../../../contracts/orbital/OrbitalMath";

const _abi = [
  {
    inputs: [],
    name: "InvalidPower",
    type: "error",
  },
  {
    inputs: [],
    name: "InvariantViolation",
    type: "error",
  },
  {
    inputs: [],
    name: "MathOverflow",
    type: "error",
  },
  {
    inputs: [],
    name: "ZeroInput",
    type: "error",
  },
] as const;

const _bytecode =
  "0x60808060405234601757603a9081601d823930815050f35b600080fdfe600080fdfea26469706673582212200dd97bbd239e00a180474b0e7cacda51e3ddb41851e11181a83ada191487789064736f6c63430008140033";

type OrbitalMathConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: OrbitalMathConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class OrbitalMath__factory extends ContractFactory {
  constructor(...args: OrbitalMathConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      OrbitalMath & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): OrbitalMath__factory {
    return super.connect(runner) as OrbitalMath__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): OrbitalMathInterface {
    return new Interface(_abi) as OrbitalMathInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): OrbitalMath {
    return new Contract(address, _abi, runner) as unknown as OrbitalMath;
  }
}
