/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as orbitalPoolSol from "./OrbitalPool.sol";
export type { orbitalPoolSol };
import type * as orbitalRouterSol from "./OrbitalRouter.sol";
export type { orbitalRouterSol };
export type { OrbitalFactory } from "./OrbitalFactory";
export type { OrbitalMath } from "./OrbitalMath";
