/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface OrbitalFactoryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "acceptAdmin"
      | "admin"
      | "createPool"
      | "defaultFeeCollector"
      | "defaultSwapFeeBps"
      | "getAllPools"
      | "getPool"
      | "getPoolAtIndex"
      | "getPools"
      | "getPoolsForToken"
      | "isRegisteredPool"
      | "pausePool"
      | "pendingAdmin"
      | "poolsByKey"
      | "setAdmin"
      | "setDefaultFeeCollector"
      | "setDefaultSwapFee"
      | "totalPools"
      | "transferAdmin"
      | "unpausePool"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AdminTransferStarted"
      | "AdminUpdated"
      | "DefaultFeeCollectorUpdated"
      | "DefaultSwapFeeUpdated"
      | "PoolCreated"
      | "PoolPaused"
      | "PoolUnpaused"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "acceptAdmin",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "admin", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "createPool",
    values: [AddressLike[], BigNumberish, BigNumberish, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "defaultFeeCollector",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "defaultSwapFeeBps",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAllPools",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPool",
    values: [AddressLike[], BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPoolAtIndex",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPools",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPoolsForToken",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isRegisteredPool",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "pausePool",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "pendingAdmin",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "poolsByKey",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setAdmin",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setDefaultFeeCollector",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setDefaultSwapFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "totalPools",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferAdmin",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "unpausePool",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "acceptAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "admin", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "createPool", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "defaultFeeCollector",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "defaultSwapFeeBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllPools",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getPool", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getPoolAtIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getPools", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getPoolsForToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isRegisteredPool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "pausePool", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pendingAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "poolsByKey", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setAdmin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setDefaultFeeCollector",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDefaultSwapFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "totalPools", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unpausePool",
    data: BytesLike
  ): Result;
}

export namespace AdminTransferStartedEvent {
  export type InputTuple = [
    currentAdmin: AddressLike,
    pendingAdmin: AddressLike
  ];
  export type OutputTuple = [currentAdmin: string, pendingAdmin: string];
  export interface OutputObject {
    currentAdmin: string;
    pendingAdmin: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AdminUpdatedEvent {
  export type InputTuple = [oldAdmin: AddressLike, newAdmin: AddressLike];
  export type OutputTuple = [oldAdmin: string, newAdmin: string];
  export interface OutputObject {
    oldAdmin: string;
    newAdmin: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DefaultFeeCollectorUpdatedEvent {
  export type InputTuple = [collector: AddressLike];
  export type OutputTuple = [collector: string];
  export interface OutputObject {
    collector: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DefaultSwapFeeUpdatedEvent {
  export type InputTuple = [newFeeBps: BigNumberish];
  export type OutputTuple = [newFeeBps: bigint];
  export interface OutputObject {
    newFeeBps: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PoolCreatedEvent {
  export type InputTuple = [
    pool: AddressLike,
    tokens: AddressLike[],
    concentration: BigNumberish,
    swapFeeBps: BigNumberish,
    feeCollector: AddressLike
  ];
  export type OutputTuple = [
    pool: string,
    tokens: string[],
    concentration: bigint,
    swapFeeBps: bigint,
    feeCollector: string
  ];
  export interface OutputObject {
    pool: string;
    tokens: string[];
    concentration: bigint;
    swapFeeBps: bigint;
    feeCollector: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PoolPausedEvent {
  export type InputTuple = [pool: AddressLike, by: AddressLike];
  export type OutputTuple = [pool: string, by: string];
  export interface OutputObject {
    pool: string;
    by: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PoolUnpausedEvent {
  export type InputTuple = [pool: AddressLike, by: AddressLike];
  export type OutputTuple = [pool: string, by: string];
  export interface OutputObject {
    pool: string;
    by: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface OrbitalFactory extends BaseContract {
  connect(runner?: ContractRunner | null): OrbitalFactory;
  waitForDeployment(): Promise<this>;

  interface: OrbitalFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  acceptAdmin: TypedContractMethod<[], [void], "nonpayable">;

  admin: TypedContractMethod<[], [string], "view">;

  createPool: TypedContractMethod<
    [
      _tokens: AddressLike[],
      _concentration: BigNumberish,
      _swapFeeBps: BigNumberish,
      _name: string,
      _symbol: string
    ],
    [string],
    "nonpayable"
  >;

  defaultFeeCollector: TypedContractMethod<[], [string], "view">;

  defaultSwapFeeBps: TypedContractMethod<[], [bigint], "view">;

  getAllPools: TypedContractMethod<[], [string[]], "view">;

  getPool: TypedContractMethod<
    [_tokens: AddressLike[], _concentration: BigNumberish],
    [string],
    "view"
  >;

  getPoolAtIndex: TypedContractMethod<[index: BigNumberish], [string], "view">;

  getPools: TypedContractMethod<
    [offset: BigNumberish, limit: BigNumberish],
    [string[]],
    "view"
  >;

  getPoolsForToken: TypedContractMethod<
    [token: AddressLike],
    [string[]],
    "view"
  >;

  isRegisteredPool: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  pausePool: TypedContractMethod<[pool: AddressLike], [void], "nonpayable">;

  pendingAdmin: TypedContractMethod<[], [string], "view">;

  poolsByKey: TypedContractMethod<[arg0: BytesLike], [string], "view">;

  setAdmin: TypedContractMethod<[_newAdmin: AddressLike], [void], "nonpayable">;

  setDefaultFeeCollector: TypedContractMethod<
    [_collector: AddressLike],
    [void],
    "nonpayable"
  >;

  setDefaultSwapFee: TypedContractMethod<
    [_feeBps: BigNumberish],
    [void],
    "nonpayable"
  >;

  totalPools: TypedContractMethod<[], [bigint], "view">;

  transferAdmin: TypedContractMethod<
    [_newAdmin: AddressLike],
    [void],
    "nonpayable"
  >;

  unpausePool: TypedContractMethod<[pool: AddressLike], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "acceptAdmin"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "admin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "createPool"
  ): TypedContractMethod<
    [
      _tokens: AddressLike[],
      _concentration: BigNumberish,
      _swapFeeBps: BigNumberish,
      _name: string,
      _symbol: string
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "defaultFeeCollector"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "defaultSwapFeeBps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getAllPools"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getPool"
  ): TypedContractMethod<
    [_tokens: AddressLike[], _concentration: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPoolAtIndex"
  ): TypedContractMethod<[index: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getPools"
  ): TypedContractMethod<
    [offset: BigNumberish, limit: BigNumberish],
    [string[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPoolsForToken"
  ): TypedContractMethod<[token: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "isRegisteredPool"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "pausePool"
  ): TypedContractMethod<[pool: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "pendingAdmin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "poolsByKey"
  ): TypedContractMethod<[arg0: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "setAdmin"
  ): TypedContractMethod<[_newAdmin: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setDefaultFeeCollector"
  ): TypedContractMethod<[_collector: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setDefaultSwapFee"
  ): TypedContractMethod<[_feeBps: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "totalPools"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferAdmin"
  ): TypedContractMethod<[_newAdmin: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unpausePool"
  ): TypedContractMethod<[pool: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "AdminTransferStarted"
  ): TypedContractEvent<
    AdminTransferStartedEvent.InputTuple,
    AdminTransferStartedEvent.OutputTuple,
    AdminTransferStartedEvent.OutputObject
  >;
  getEvent(
    key: "AdminUpdated"
  ): TypedContractEvent<
    AdminUpdatedEvent.InputTuple,
    AdminUpdatedEvent.OutputTuple,
    AdminUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "DefaultFeeCollectorUpdated"
  ): TypedContractEvent<
    DefaultFeeCollectorUpdatedEvent.InputTuple,
    DefaultFeeCollectorUpdatedEvent.OutputTuple,
    DefaultFeeCollectorUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "DefaultSwapFeeUpdated"
  ): TypedContractEvent<
    DefaultSwapFeeUpdatedEvent.InputTuple,
    DefaultSwapFeeUpdatedEvent.OutputTuple,
    DefaultSwapFeeUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "PoolCreated"
  ): TypedContractEvent<
    PoolCreatedEvent.InputTuple,
    PoolCreatedEvent.OutputTuple,
    PoolCreatedEvent.OutputObject
  >;
  getEvent(
    key: "PoolPaused"
  ): TypedContractEvent<
    PoolPausedEvent.InputTuple,
    PoolPausedEvent.OutputTuple,
    PoolPausedEvent.OutputObject
  >;
  getEvent(
    key: "PoolUnpaused"
  ): TypedContractEvent<
    PoolUnpausedEvent.InputTuple,
    PoolUnpausedEvent.OutputTuple,
    PoolUnpausedEvent.OutputObject
  >;

  filters: {
    "AdminTransferStarted(address,address)": TypedContractEvent<
      AdminTransferStartedEvent.InputTuple,
      AdminTransferStartedEvent.OutputTuple,
      AdminTransferStartedEvent.OutputObject
    >;
    AdminTransferStarted: TypedContractEvent<
      AdminTransferStartedEvent.InputTuple,
      AdminTransferStartedEvent.OutputTuple,
      AdminTransferStartedEvent.OutputObject
    >;

    "AdminUpdated(address,address)": TypedContractEvent<
      AdminUpdatedEvent.InputTuple,
      AdminUpdatedEvent.OutputTuple,
      AdminUpdatedEvent.OutputObject
    >;
    AdminUpdated: TypedContractEvent<
      AdminUpdatedEvent.InputTuple,
      AdminUpdatedEvent.OutputTuple,
      AdminUpdatedEvent.OutputObject
    >;

    "DefaultFeeCollectorUpdated(address)": TypedContractEvent<
      DefaultFeeCollectorUpdatedEvent.InputTuple,
      DefaultFeeCollectorUpdatedEvent.OutputTuple,
      DefaultFeeCollectorUpdatedEvent.OutputObject
    >;
    DefaultFeeCollectorUpdated: TypedContractEvent<
      DefaultFeeCollectorUpdatedEvent.InputTuple,
      DefaultFeeCollectorUpdatedEvent.OutputTuple,
      DefaultFeeCollectorUpdatedEvent.OutputObject
    >;

    "DefaultSwapFeeUpdated(uint256)": TypedContractEvent<
      DefaultSwapFeeUpdatedEvent.InputTuple,
      DefaultSwapFeeUpdatedEvent.OutputTuple,
      DefaultSwapFeeUpdatedEvent.OutputObject
    >;
    DefaultSwapFeeUpdated: TypedContractEvent<
      DefaultSwapFeeUpdatedEvent.InputTuple,
      DefaultSwapFeeUpdatedEvent.OutputTuple,
      DefaultSwapFeeUpdatedEvent.OutputObject
    >;

    "PoolCreated(address,address[],uint8,uint256,address)": TypedContractEvent<
      PoolCreatedEvent.InputTuple,
      PoolCreatedEvent.OutputTuple,
      PoolCreatedEvent.OutputObject
    >;
    PoolCreated: TypedContractEvent<
      PoolCreatedEvent.InputTuple,
      PoolCreatedEvent.OutputTuple,
      PoolCreatedEvent.OutputObject
    >;

    "PoolPaused(address,address)": TypedContractEvent<
      PoolPausedEvent.InputTuple,
      PoolPausedEvent.OutputTuple,
      PoolPausedEvent.OutputObject
    >;
    PoolPaused: TypedContractEvent<
      PoolPausedEvent.InputTuple,
      PoolPausedEvent.OutputTuple,
      PoolPausedEvent.OutputObject
    >;

    "PoolUnpaused(address,address)": TypedContractEvent<
      PoolUnpausedEvent.InputTuple,
      PoolUnpausedEvent.OutputTuple,
      PoolUnpausedEvent.OutputObject
    >;
    PoolUnpaused: TypedContractEvent<
      PoolUnpausedEvent.InputTuple,
      PoolUnpausedEvent.OutputTuple,
      PoolUnpausedEvent.OutputObject
    >;
  };
}
