/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace AssetBackedExchange {
  export type OrderStruct = {
    id: BigNumberish;
    maker: AddressLike;
    tokenSell: AddressLike;
    tokenBuy: AddressLike;
    amountSell: BigNumberish;
    amountBuy: BigNumberish;
    filledSell: BigNumberish;
    filledBuy: BigNumberish;
    cancelled: boolean;
    deadline: BigNumberish;
  };

  export type OrderStructOutput = [
    id: bigint,
    maker: string,
    tokenSell: string,
    tokenBuy: string,
    amountSell: bigint,
    amountBuy: bigint,
    filledSell: bigint,
    filledBuy: bigint,
    cancelled: boolean,
    deadline: bigint
  ] & {
    id: bigint;
    maker: string;
    tokenSell: string;
    tokenBuy: string;
    amountSell: bigint;
    amountBuy: bigint;
    filledSell: bigint;
    filledBuy: bigint;
    cancelled: boolean;
    deadline: bigint;
  };
}

export interface AssetBackedExchangeInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "EMERGENCY_TIMELOCK"
      | "ETH_ADDRESS"
      | "MAX_SCAN_LIMIT"
      | "acceptOwnership"
      | "cancelEmergencyWithdraw"
      | "cancelOrder"
      | "createOrder"
      | "createOrderSellETH"
      | "emergencyRequests"
      | "ethBalances"
      | "executeEmergencyWithdraw"
      | "fillOrder"
      | "fillOrderWithETH"
      | "getActiveOrders(address,address)"
      | "getActiveOrders(address,address,uint256,uint256)"
      | "getOrder"
      | "getOrderCount"
      | "getUserOrders"
      | "nextEmergencyId"
      | "nextOrderId"
      | "owner"
      | "pause"
      | "paused"
      | "pendingOwner"
      | "requestEmergencyWithdraw"
      | "transferOwnership"
      | "unpause"
      | "withdrawEth"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "EmergencyWithdrawCancelled"
      | "EmergencyWithdrawExecuted"
      | "EmergencyWithdrawRequested"
      | "EthWithdrawn"
      | "OrderCancelled"
      | "OrderCreated"
      | "OrderFilled"
      | "OwnershipTransferStarted"
      | "OwnershipTransferred"
      | "Paused"
      | "Unpaused"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "EMERGENCY_TIMELOCK",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ETH_ADDRESS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_SCAN_LIMIT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "acceptOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "cancelEmergencyWithdraw",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelOrder",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createOrder",
    values: [AddressLike, AddressLike, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createOrderSellETH",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyRequests",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "ethBalances",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "executeEmergencyWithdraw",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "fillOrder",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "fillOrderWithETH",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getActiveOrders(address,address)",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getActiveOrders(address,address,uint256,uint256)",
    values: [AddressLike, AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getOrder",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getOrderCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getUserOrders",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "nextEmergencyId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "nextOrderId",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pendingOwner",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "requestEmergencyWithdraw",
    values: [AddressLike, BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "withdrawEth",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "EMERGENCY_TIMELOCK",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ETH_ADDRESS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_SCAN_LIMIT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "acceptOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelEmergencyWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelOrder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createOrder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createOrderSellETH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyRequests",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ethBalances",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeEmergencyWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "fillOrder", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "fillOrderWithETH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getActiveOrders(address,address)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getActiveOrders(address,address,uint256,uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getOrder", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getOrderCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserOrders",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nextEmergencyId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nextOrderId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pendingOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestEmergencyWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawEth",
    data: BytesLike
  ): Result;
}

export namespace EmergencyWithdrawCancelledEvent {
  export type InputTuple = [requestId: BigNumberish];
  export type OutputTuple = [requestId: bigint];
  export interface OutputObject {
    requestId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EmergencyWithdrawExecutedEvent {
  export type InputTuple = [requestId: BigNumberish];
  export type OutputTuple = [requestId: bigint];
  export interface OutputObject {
    requestId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EmergencyWithdrawRequestedEvent {
  export type InputTuple = [
    requestId: BigNumberish,
    token: AddressLike,
    amount: BigNumberish,
    recipient: AddressLike,
    executeAfter: BigNumberish
  ];
  export type OutputTuple = [
    requestId: bigint,
    token: string,
    amount: bigint,
    recipient: string,
    executeAfter: bigint
  ];
  export interface OutputObject {
    requestId: bigint;
    token: string;
    amount: bigint;
    recipient: string;
    executeAfter: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EthWithdrawnEvent {
  export type InputTuple = [to: AddressLike, amount: BigNumberish];
  export type OutputTuple = [to: string, amount: bigint];
  export interface OutputObject {
    to: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OrderCancelledEvent {
  export type InputTuple = [orderId: BigNumberish, maker: AddressLike];
  export type OutputTuple = [orderId: bigint, maker: string];
  export interface OutputObject {
    orderId: bigint;
    maker: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OrderCreatedEvent {
  export type InputTuple = [
    orderId: BigNumberish,
    maker: AddressLike,
    tokenSell: AddressLike,
    tokenBuy: AddressLike,
    amountSell: BigNumberish,
    amountBuy: BigNumberish,
    deadline: BigNumberish
  ];
  export type OutputTuple = [
    orderId: bigint,
    maker: string,
    tokenSell: string,
    tokenBuy: string,
    amountSell: bigint,
    amountBuy: bigint,
    deadline: bigint
  ];
  export interface OutputObject {
    orderId: bigint;
    maker: string;
    tokenSell: string;
    tokenBuy: string;
    amountSell: bigint;
    amountBuy: bigint;
    deadline: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OrderFilledEvent {
  export type InputTuple = [
    orderId: BigNumberish,
    taker: AddressLike,
    fillAmountSell: BigNumberish,
    fillAmountBuy: BigNumberish
  ];
  export type OutputTuple = [
    orderId: bigint,
    taker: string,
    fillAmountSell: bigint,
    fillAmountBuy: bigint
  ];
  export interface OutputObject {
    orderId: bigint;
    taker: string;
    fillAmountSell: bigint;
    fillAmountBuy: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferStartedEvent {
  export type InputTuple = [
    currentOwner: AddressLike,
    pendingOwner: AddressLike
  ];
  export type OutputTuple = [currentOwner: string, pendingOwner: string];
  export interface OutputObject {
    currentOwner: string;
    pendingOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [by: AddressLike];
  export type OutputTuple = [by: string];
  export interface OutputObject {
    by: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [by: AddressLike];
  export type OutputTuple = [by: string];
  export interface OutputObject {
    by: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AssetBackedExchange extends BaseContract {
  connect(runner?: ContractRunner | null): AssetBackedExchange;
  waitForDeployment(): Promise<this>;

  interface: AssetBackedExchangeInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  EMERGENCY_TIMELOCK: TypedContractMethod<[], [bigint], "view">;

  ETH_ADDRESS: TypedContractMethod<[], [string], "view">;

  MAX_SCAN_LIMIT: TypedContractMethod<[], [bigint], "view">;

  acceptOwnership: TypedContractMethod<[], [void], "nonpayable">;

  cancelEmergencyWithdraw: TypedContractMethod<
    [requestId: BigNumberish],
    [void],
    "nonpayable"
  >;

  cancelOrder: TypedContractMethod<
    [orderId: BigNumberish],
    [void],
    "nonpayable"
  >;

  createOrder: TypedContractMethod<
    [
      tokenSell: AddressLike,
      tokenBuy: AddressLike,
      amountSell: BigNumberish,
      amountBuy: BigNumberish,
      deadline: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  createOrderSellETH: TypedContractMethod<
    [tokenBuy: AddressLike, amountBuy: BigNumberish, deadline: BigNumberish],
    [bigint],
    "payable"
  >;

  emergencyRequests: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, string, bigint, boolean] & {
        token: string;
        amount: bigint;
        recipient: string;
        executeAfter: bigint;
        executed: boolean;
      }
    ],
    "view"
  >;

  ethBalances: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  executeEmergencyWithdraw: TypedContractMethod<
    [requestId: BigNumberish],
    [void],
    "nonpayable"
  >;

  fillOrder: TypedContractMethod<
    [orderId: BigNumberish, fillAmountBuy: BigNumberish],
    [void],
    "nonpayable"
  >;

  fillOrderWithETH: TypedContractMethod<
    [orderId: BigNumberish],
    [void],
    "payable"
  >;

  "getActiveOrders(address,address)": TypedContractMethod<
    [tokenSell: AddressLike, tokenBuy: AddressLike],
    [AssetBackedExchange.OrderStructOutput[]],
    "view"
  >;

  "getActiveOrders(address,address,uint256,uint256)": TypedContractMethod<
    [
      tokenSell: AddressLike,
      tokenBuy: AddressLike,
      offset: BigNumberish,
      limit: BigNumberish
    ],
    [AssetBackedExchange.OrderStructOutput[]],
    "view"
  >;

  getOrder: TypedContractMethod<
    [orderId: BigNumberish],
    [AssetBackedExchange.OrderStructOutput],
    "view"
  >;

  getOrderCount: TypedContractMethod<[], [bigint], "view">;

  getUserOrders: TypedContractMethod<[user: AddressLike], [bigint[]], "view">;

  nextEmergencyId: TypedContractMethod<[], [bigint], "view">;

  nextOrderId: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  pendingOwner: TypedContractMethod<[], [string], "view">;

  requestEmergencyWithdraw: TypedContractMethod<
    [token: AddressLike, amount: BigNumberish, recipient: AddressLike],
    [bigint],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  withdrawEth: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "EMERGENCY_TIMELOCK"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "ETH_ADDRESS"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "MAX_SCAN_LIMIT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "acceptOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "cancelEmergencyWithdraw"
  ): TypedContractMethod<[requestId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "cancelOrder"
  ): TypedContractMethod<[orderId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createOrder"
  ): TypedContractMethod<
    [
      tokenSell: AddressLike,
      tokenBuy: AddressLike,
      amountSell: BigNumberish,
      amountBuy: BigNumberish,
      deadline: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createOrderSellETH"
  ): TypedContractMethod<
    [tokenBuy: AddressLike, amountBuy: BigNumberish, deadline: BigNumberish],
    [bigint],
    "payable"
  >;
  getFunction(
    nameOrSignature: "emergencyRequests"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, string, bigint, boolean] & {
        token: string;
        amount: bigint;
        recipient: string;
        executeAfter: bigint;
        executed: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "ethBalances"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "executeEmergencyWithdraw"
  ): TypedContractMethod<[requestId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "fillOrder"
  ): TypedContractMethod<
    [orderId: BigNumberish, fillAmountBuy: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "fillOrderWithETH"
  ): TypedContractMethod<[orderId: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "getActiveOrders(address,address)"
  ): TypedContractMethod<
    [tokenSell: AddressLike, tokenBuy: AddressLike],
    [AssetBackedExchange.OrderStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getActiveOrders(address,address,uint256,uint256)"
  ): TypedContractMethod<
    [
      tokenSell: AddressLike,
      tokenBuy: AddressLike,
      offset: BigNumberish,
      limit: BigNumberish
    ],
    [AssetBackedExchange.OrderStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getOrder"
  ): TypedContractMethod<
    [orderId: BigNumberish],
    [AssetBackedExchange.OrderStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getOrderCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getUserOrders"
  ): TypedContractMethod<[user: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "nextEmergencyId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "nextOrderId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "pendingOwner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "requestEmergencyWithdraw"
  ): TypedContractMethod<
    [token: AddressLike, amount: BigNumberish, recipient: AddressLike],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawEth"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "EmergencyWithdrawCancelled"
  ): TypedContractEvent<
    EmergencyWithdrawCancelledEvent.InputTuple,
    EmergencyWithdrawCancelledEvent.OutputTuple,
    EmergencyWithdrawCancelledEvent.OutputObject
  >;
  getEvent(
    key: "EmergencyWithdrawExecuted"
  ): TypedContractEvent<
    EmergencyWithdrawExecutedEvent.InputTuple,
    EmergencyWithdrawExecutedEvent.OutputTuple,
    EmergencyWithdrawExecutedEvent.OutputObject
  >;
  getEvent(
    key: "EmergencyWithdrawRequested"
  ): TypedContractEvent<
    EmergencyWithdrawRequestedEvent.InputTuple,
    EmergencyWithdrawRequestedEvent.OutputTuple,
    EmergencyWithdrawRequestedEvent.OutputObject
  >;
  getEvent(
    key: "EthWithdrawn"
  ): TypedContractEvent<
    EthWithdrawnEvent.InputTuple,
    EthWithdrawnEvent.OutputTuple,
    EthWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "OrderCancelled"
  ): TypedContractEvent<
    OrderCancelledEvent.InputTuple,
    OrderCancelledEvent.OutputTuple,
    OrderCancelledEvent.OutputObject
  >;
  getEvent(
    key: "OrderCreated"
  ): TypedContractEvent<
    OrderCreatedEvent.InputTuple,
    OrderCreatedEvent.OutputTuple,
    OrderCreatedEvent.OutputObject
  >;
  getEvent(
    key: "OrderFilled"
  ): TypedContractEvent<
    OrderFilledEvent.InputTuple,
    OrderFilledEvent.OutputTuple,
    OrderFilledEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferStarted"
  ): TypedContractEvent<
    OwnershipTransferStartedEvent.InputTuple,
    OwnershipTransferStartedEvent.OutputTuple,
    OwnershipTransferStartedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;

  filters: {
    "EmergencyWithdrawCancelled(uint256)": TypedContractEvent<
      EmergencyWithdrawCancelledEvent.InputTuple,
      EmergencyWithdrawCancelledEvent.OutputTuple,
      EmergencyWithdrawCancelledEvent.OutputObject
    >;
    EmergencyWithdrawCancelled: TypedContractEvent<
      EmergencyWithdrawCancelledEvent.InputTuple,
      EmergencyWithdrawCancelledEvent.OutputTuple,
      EmergencyWithdrawCancelledEvent.OutputObject
    >;

    "EmergencyWithdrawExecuted(uint256)": TypedContractEvent<
      EmergencyWithdrawExecutedEvent.InputTuple,
      EmergencyWithdrawExecutedEvent.OutputTuple,
      EmergencyWithdrawExecutedEvent.OutputObject
    >;
    EmergencyWithdrawExecuted: TypedContractEvent<
      EmergencyWithdrawExecutedEvent.InputTuple,
      EmergencyWithdrawExecutedEvent.OutputTuple,
      EmergencyWithdrawExecutedEvent.OutputObject
    >;

    "EmergencyWithdrawRequested(uint256,address,uint256,address,uint256)": TypedContractEvent<
      EmergencyWithdrawRequestedEvent.InputTuple,
      EmergencyWithdrawRequestedEvent.OutputTuple,
      EmergencyWithdrawRequestedEvent.OutputObject
    >;
    EmergencyWithdrawRequested: TypedContractEvent<
      EmergencyWithdrawRequestedEvent.InputTuple,
      EmergencyWithdrawRequestedEvent.OutputTuple,
      EmergencyWithdrawRequestedEvent.OutputObject
    >;

    "EthWithdrawn(address,uint256)": TypedContractEvent<
      EthWithdrawnEvent.InputTuple,
      EthWithdrawnEvent.OutputTuple,
      EthWithdrawnEvent.OutputObject
    >;
    EthWithdrawn: TypedContractEvent<
      EthWithdrawnEvent.InputTuple,
      EthWithdrawnEvent.OutputTuple,
      EthWithdrawnEvent.OutputObject
    >;

    "OrderCancelled(uint256,address)": TypedContractEvent<
      OrderCancelledEvent.InputTuple,
      OrderCancelledEvent.OutputTuple,
      OrderCancelledEvent.OutputObject
    >;
    OrderCancelled: TypedContractEvent<
      OrderCancelledEvent.InputTuple,
      OrderCancelledEvent.OutputTuple,
      OrderCancelledEvent.OutputObject
    >;

    "OrderCreated(uint256,address,address,address,uint256,uint256,uint256)": TypedContractEvent<
      OrderCreatedEvent.InputTuple,
      OrderCreatedEvent.OutputTuple,
      OrderCreatedEvent.OutputObject
    >;
    OrderCreated: TypedContractEvent<
      OrderCreatedEvent.InputTuple,
      OrderCreatedEvent.OutputTuple,
      OrderCreatedEvent.OutputObject
    >;

    "OrderFilled(uint256,address,uint256,uint256)": TypedContractEvent<
      OrderFilledEvent.InputTuple,
      OrderFilledEvent.OutputTuple,
      OrderFilledEvent.OutputObject
    >;
    OrderFilled: TypedContractEvent<
      OrderFilledEvent.InputTuple,
      OrderFilledEvent.OutputTuple,
      OrderFilledEvent.OutputObject
    >;

    "OwnershipTransferStarted(address,address)": TypedContractEvent<
      OwnershipTransferStartedEvent.InputTuple,
      OwnershipTransferStartedEvent.OutputTuple,
      OwnershipTransferStartedEvent.OutputObject
    >;
    OwnershipTransferStarted: TypedContractEvent<
      OwnershipTransferStartedEvent.InputTuple,
      OwnershipTransferStartedEvent.OutputTuple,
      OwnershipTransferStartedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
  };
}
