/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface EasyAccessControlInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "contractAdminCount"
      | "grantRole"
      | "hasRole"
      | "revokeRole"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "RoleChange"): EventFragment;

  encodeFunctionData(
    functionFragment: "contractAdminCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "contractAdminCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
}

export namespace RoleChangeEvent {
  export type InputTuple = [
    grantor: AddressLike,
    grantee: AddressLike,
    role: BigNumberish,
    status: boolean
  ];
  export type OutputTuple = [
    grantor: string,
    grantee: string,
    role: bigint,
    status: boolean
  ];
  export interface OutputObject {
    grantor: string;
    grantee: string;
    role: bigint;
    status: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface EasyAccessControl extends BaseContract {
  connect(runner?: ContractRunner | null): EasyAccessControl;
  waitForDeployment(): Promise<this>;

  interface: EasyAccessControlInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  contractAdminCount: TypedContractMethod<[], [bigint], "view">;

  grantRole: TypedContractMethod<
    [addr: AddressLike, role: BigNumberish],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [addr: AddressLike, role: BigNumberish],
    [boolean],
    "view"
  >;

  revokeRole: TypedContractMethod<
    [addr: AddressLike, role: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "contractAdminCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [addr: AddressLike, role: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [addr: AddressLike, role: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [addr: AddressLike, role: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "RoleChange"
  ): TypedContractEvent<
    RoleChangeEvent.InputTuple,
    RoleChangeEvent.OutputTuple,
    RoleChangeEvent.OutputObject
  >;

  filters: {
    "RoleChange(address,address,uint8,bool)": TypedContractEvent<
      RoleChangeEvent.InputTuple,
      RoleChangeEvent.OutputTuple,
      RoleChangeEvent.OutputObject
    >;
    RoleChange: TypedContractEvent<
      RoleChangeEvent.InputTuple,
      RoleChangeEvent.OutputTuple,
      RoleChangeEvent.OutputObject
    >;
  };
}
