/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace RestrictedLockupToken {
  export type ReleaseScheduleStruct = {
    releaseCount: BigNumberish;
    delayUntilFirstReleaseInSeconds: BigNumberish;
    initialReleasePortionInBips: BigNumberish;
    periodBetweenReleasesInSeconds: BigNumberish;
  };

  export type ReleaseScheduleStructOutput = [
    releaseCount: bigint,
    delayUntilFirstReleaseInSeconds: bigint,
    initialReleasePortionInBips: bigint,
    periodBetweenReleasesInSeconds: bigint
  ] & {
    releaseCount: bigint;
    delayUntilFirstReleaseInSeconds: bigint;
    initialReleasePortionInBips: bigint;
    periodBetweenReleasesInSeconds: bigint;
  };

  export type TimelockStruct = {
    scheduleId: BigNumberish;
    commencementTimestamp: BigNumberish;
    tokensTransferred: BigNumberish;
    totalAmount: BigNumberish;
    cancelableBy: AddressLike[];
  };

  export type TimelockStructOutput = [
    scheduleId: bigint,
    commencementTimestamp: bigint,
    tokensTransferred: bigint,
    totalAmount: bigint,
    cancelableBy: string[]
  ] & {
    scheduleId: bigint;
    commencementTimestamp: bigint;
    tokensTransferred: bigint;
    totalAmount: bigint;
    cancelableBy: string[];
  };
}

export interface RestrictedLockupTokenInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "_decimals"
      | "allowance"
      | "approve"
      | "balanceOf"
      | "balanceOfAt"
      | "balanceOfTimelock"
      | "batchFundReleaseSchedule"
      | "burn"
      | "calculateUnlocked(uint256,uint256,uint256,(uint256,uint256,uint256,uint256))"
      | "calculateUnlocked(uint256,uint256,uint256,uint256,uint256,uint256,uint256)"
      | "calculateUnlocked(uint256,uint256,uint256,uint256)"
      | "cancelTimelock"
      | "contractAdminCount"
      | "createReleaseSchedule"
      | "decimals"
      | "decreaseAllowance"
      | "detectTransferRestriction"
      | "enforceTransferRestrictions"
      | "freeze"
      | "fundReleaseSchedule"
      | "getAllowGroupTransferTime"
      | "getAllowTransferTime"
      | "getCurrentSnapshotId"
      | "getFrozenStatus"
      | "getMaxBalance"
      | "getTransferGroup"
      | "grantRole"
      | "hasRole"
      | "increaseAllowance"
      | "isPaused"
      | "lockedAmountOf"
      | "lockedAmountOfTimelock"
      | "maxReleaseDelay"
      | "maxTotalSupply"
      | "messageForTransferRestriction"
      | "minTimelockAmount"
      | "mint"
      | "name"
      | "pause"
      | "releaseSchedules"
      | "revokeRole"
      | "safeApprove"
      | "scheduleCount"
      | "setAddressPermissions"
      | "setAllowGroupTransfer"
      | "setMaxBalance"
      | "setTransferGroup"
      | "snapshot"
      | "symbol"
      | "timelockBalanceOf"
      | "timelockCountOf"
      | "timelockOf"
      | "timelocks"
      | "tokensBalanceOf"
      | "totalSupply"
      | "totalSupplyAt"
      | "totalUnlockedToDateOfTimelock"
      | "transfer"
      | "transferFrom"
      | "transferRules"
      | "transferTimelock"
      | "unlockedAmountOf"
      | "unlockedAmountOfTimelock"
      | "unlockedBalanceOf"
      | "unpause"
      | "upgradeTransferRules"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AddressFrozen"
      | "AddressMaxBalance"
      | "AddressTransferGroup"
      | "AllowGroupTransfer"
      | "Approval"
      | "Pause"
      | "RoleChange"
      | "ScheduleCreated"
      | "ScheduleFunded"
      | "Snapshot"
      | "TimelockCanceled"
      | "Transfer"
      | "Upgrade"
  ): EventFragment;

  encodeFunctionData(functionFragment: "_decimals", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "allowance",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "approve",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "balanceOf",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "balanceOfAt",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "balanceOfTimelock",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "batchFundReleaseSchedule",
    values: [
      AddressLike[],
      BigNumberish[],
      BigNumberish[],
      BigNumberish[],
      AddressLike[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "burn",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "calculateUnlocked(uint256,uint256,uint256,(uint256,uint256,uint256,uint256))",
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      RestrictedLockupToken.ReleaseScheduleStruct
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "calculateUnlocked(uint256,uint256,uint256,uint256,uint256,uint256,uint256)",
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "calculateUnlocked(uint256,uint256,uint256,uint256)",
    values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelTimelock",
    values: [
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      AddressLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "contractAdminCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "createReleaseSchedule",
    values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "decimals", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "decreaseAllowance",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "detectTransferRestriction",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "enforceTransferRestrictions",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "freeze",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "fundReleaseSchedule",
    values: [
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      AddressLike[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllowGroupTransferTime",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllowTransferTime",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getCurrentSnapshotId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getFrozenStatus",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getMaxBalance",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTransferGroup",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "increaseAllowance",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "isPaused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "lockedAmountOf",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lockedAmountOfTimelock",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "maxReleaseDelay",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "maxTotalSupply",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "messageForTransferRestriction",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "minTimelockAmount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "mint",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "name", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "releaseSchedules",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "safeApprove",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "scheduleCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setAddressPermissions",
    values: [AddressLike, BigNumberish, BigNumberish, BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setAllowGroupTransfer",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setMaxBalance",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setTransferGroup",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "snapshot", values?: undefined): string;
  encodeFunctionData(functionFragment: "symbol", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "timelockBalanceOf",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "timelockCountOf",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "timelockOf",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "timelocks",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "tokensBalanceOf",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "totalSupply",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalSupplyAt",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "totalUnlockedToDateOfTimelock",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transfer",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferFrom",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferRules",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferTimelock",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "unlockedAmountOf",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "unlockedAmountOfTimelock",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "unlockedBalanceOf",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "upgradeTransferRules",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "_decimals", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "allowance", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "approve", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "balanceOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "balanceOfAt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "balanceOfTimelock",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "batchFundReleaseSchedule",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "burn", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "calculateUnlocked(uint256,uint256,uint256,(uint256,uint256,uint256,uint256))",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculateUnlocked(uint256,uint256,uint256,uint256,uint256,uint256,uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculateUnlocked(uint256,uint256,uint256,uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelTimelock",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "contractAdminCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createReleaseSchedule",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "decimals", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "decreaseAllowance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "detectTransferRestriction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "enforceTransferRestrictions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "freeze", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "fundReleaseSchedule",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllowGroupTransferTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllowTransferTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCurrentSnapshotId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getFrozenStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMaxBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTransferGroup",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "increaseAllowance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isPaused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "lockedAmountOf",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lockedAmountOfTimelock",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "maxReleaseDelay",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "maxTotalSupply",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "messageForTransferRestriction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "minTimelockAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "mint", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "name", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "releaseSchedules",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "safeApprove",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "scheduleCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAddressPermissions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAllowGroupTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMaxBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTransferGroup",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "snapshot", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "symbol", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "timelockBalanceOf",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "timelockCountOf",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "timelockOf", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "timelocks", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "tokensBalanceOf",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalSupply",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalSupplyAt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalUnlockedToDateOfTimelock",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "transfer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferFrom",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferRules",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferTimelock",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unlockedAmountOf",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unlockedAmountOfTimelock",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unlockedBalanceOf",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "upgradeTransferRules",
    data: BytesLike
  ): Result;
}

export namespace AddressFrozenEvent {
  export type InputTuple = [
    admin: AddressLike,
    addr: AddressLike,
    status: boolean
  ];
  export type OutputTuple = [admin: string, addr: string, status: boolean];
  export interface OutputObject {
    admin: string;
    addr: string;
    status: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AddressMaxBalanceEvent {
  export type InputTuple = [
    admin: AddressLike,
    addr: AddressLike,
    value: BigNumberish
  ];
  export type OutputTuple = [admin: string, addr: string, value: bigint];
  export interface OutputObject {
    admin: string;
    addr: string;
    value: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AddressTransferGroupEvent {
  export type InputTuple = [
    admin: AddressLike,
    addr: AddressLike,
    value: BigNumberish
  ];
  export type OutputTuple = [admin: string, addr: string, value: bigint];
  export interface OutputObject {
    admin: string;
    addr: string;
    value: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AllowGroupTransferEvent {
  export type InputTuple = [
    admin: AddressLike,
    fromGroup: BigNumberish,
    toGroup: BigNumberish,
    lockedUntil: BigNumberish
  ];
  export type OutputTuple = [
    admin: string,
    fromGroup: bigint,
    toGroup: bigint,
    lockedUntil: bigint
  ];
  export interface OutputObject {
    admin: string;
    fromGroup: bigint;
    toGroup: bigint;
    lockedUntil: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ApprovalEvent {
  export type InputTuple = [
    owner: AddressLike,
    spender: AddressLike,
    value: BigNumberish
  ];
  export type OutputTuple = [owner: string, spender: string, value: bigint];
  export interface OutputObject {
    owner: string;
    spender: string;
    value: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PauseEvent {
  export type InputTuple = [admin: AddressLike, status: boolean];
  export type OutputTuple = [admin: string, status: boolean];
  export interface OutputObject {
    admin: string;
    status: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleChangeEvent {
  export type InputTuple = [
    grantor: AddressLike,
    grantee: AddressLike,
    role: BigNumberish,
    status: boolean
  ];
  export type OutputTuple = [
    grantor: string,
    grantee: string,
    role: bigint,
    status: boolean
  ];
  export interface OutputObject {
    grantor: string;
    grantee: string;
    role: bigint;
    status: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ScheduleCreatedEvent {
  export type InputTuple = [from: AddressLike, scheduleId: BigNumberish];
  export type OutputTuple = [from: string, scheduleId: bigint];
  export interface OutputObject {
    from: string;
    scheduleId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ScheduleFundedEvent {
  export type InputTuple = [
    from: AddressLike,
    to: AddressLike,
    scheduleId: BigNumberish,
    amount: BigNumberish,
    commencementTimestamp: BigNumberish,
    timelockId: BigNumberish,
    cancelableBy: AddressLike[]
  ];
  export type OutputTuple = [
    from: string,
    to: string,
    scheduleId: bigint,
    amount: bigint,
    commencementTimestamp: bigint,
    timelockId: bigint,
    cancelableBy: string[]
  ];
  export interface OutputObject {
    from: string;
    to: string;
    scheduleId: bigint;
    amount: bigint;
    commencementTimestamp: bigint;
    timelockId: bigint;
    cancelableBy: string[];
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SnapshotEvent {
  export type InputTuple = [id: BigNumberish];
  export type OutputTuple = [id: bigint];
  export interface OutputObject {
    id: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TimelockCanceledEvent {
  export type InputTuple = [
    canceledBy: AddressLike,
    target: AddressLike,
    timelockIndex: BigNumberish,
    relaimTokenTo: AddressLike,
    canceledAmount: BigNumberish,
    paidAmount: BigNumberish
  ];
  export type OutputTuple = [
    canceledBy: string,
    target: string,
    timelockIndex: bigint,
    relaimTokenTo: string,
    canceledAmount: bigint,
    paidAmount: bigint
  ];
  export interface OutputObject {
    canceledBy: string;
    target: string;
    timelockIndex: bigint;
    relaimTokenTo: string;
    canceledAmount: bigint;
    paidAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransferEvent {
  export type InputTuple = [
    from: AddressLike,
    to: AddressLike,
    value: BigNumberish
  ];
  export type OutputTuple = [from: string, to: string, value: bigint];
  export interface OutputObject {
    from: string;
    to: string;
    value: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpgradeEvent {
  export type InputTuple = [
    admin: AddressLike,
    oldRules: AddressLike,
    newRules: AddressLike
  ];
  export type OutputTuple = [admin: string, oldRules: string, newRules: string];
  export interface OutputObject {
    admin: string;
    oldRules: string;
    newRules: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface RestrictedLockupToken extends BaseContract {
  connect(runner?: ContractRunner | null): RestrictedLockupToken;
  waitForDeployment(): Promise<this>;

  interface: RestrictedLockupTokenInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  _decimals: TypedContractMethod<[], [bigint], "view">;

  allowance: TypedContractMethod<
    [owner: AddressLike, spender: AddressLike],
    [bigint],
    "view"
  >;

  approve: TypedContractMethod<
    [spender: AddressLike, amount: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  balanceOf: TypedContractMethod<[who: AddressLike], [bigint], "view">;

  balanceOfAt: TypedContractMethod<
    [account: AddressLike, snapshotId: BigNumberish],
    [bigint],
    "view"
  >;

  balanceOfTimelock: TypedContractMethod<
    [who: AddressLike, timelockIndex: BigNumberish],
    [bigint],
    "view"
  >;

  batchFundReleaseSchedule: TypedContractMethod<
    [
      to: AddressLike[],
      amounts: BigNumberish[],
      commencementTimestamps: BigNumberish[],
      scheduleIds: BigNumberish[],
      cancelableBy: AddressLike[]
    ],
    [boolean],
    "nonpayable"
  >;

  burn: TypedContractMethod<
    [from: AddressLike, value: BigNumberish],
    [void],
    "nonpayable"
  >;

  "calculateUnlocked(uint256,uint256,uint256,(uint256,uint256,uint256,uint256))": TypedContractMethod<
    [
      commencedTimestamp: BigNumberish,
      currentTimestamp: BigNumberish,
      amount: BigNumberish,
      releaseSchedule: RestrictedLockupToken.ReleaseScheduleStruct
    ],
    [bigint],
    "view"
  >;

  "calculateUnlocked(uint256,uint256,uint256,uint256,uint256,uint256,uint256)": TypedContractMethod<
    [
      commencedTimestamp: BigNumberish,
      currentTimestamp: BigNumberish,
      amount: BigNumberish,
      releaseCount: BigNumberish,
      delayUntilFirstReleaseInSeconds: BigNumberish,
      initialReleasePortionInBips: BigNumberish,
      periodBetweenReleasesInSeconds: BigNumberish
    ],
    [bigint],
    "view"
  >;

  "calculateUnlocked(uint256,uint256,uint256,uint256)": TypedContractMethod<
    [
      commencedTimestamp: BigNumberish,
      currentTimestamp: BigNumberish,
      amount: BigNumberish,
      scheduleId: BigNumberish
    ],
    [bigint],
    "view"
  >;

  cancelTimelock: TypedContractMethod<
    [
      target: AddressLike,
      timelockIndex: BigNumberish,
      scheduleId: BigNumberish,
      commencementTimestamp: BigNumberish,
      totalAmount: BigNumberish,
      reclaimTokenTo: AddressLike
    ],
    [boolean],
    "nonpayable"
  >;

  contractAdminCount: TypedContractMethod<[], [bigint], "view">;

  createReleaseSchedule: TypedContractMethod<
    [
      releaseCount: BigNumberish,
      delayUntilFirstReleaseInSeconds: BigNumberish,
      initialReleasePortionInBips: BigNumberish,
      periodBetweenReleasesInSeconds: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  decimals: TypedContractMethod<[], [bigint], "view">;

  decreaseAllowance: TypedContractMethod<
    [spender: AddressLike, subtractedValue: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  detectTransferRestriction: TypedContractMethod<
    [from: AddressLike, to: AddressLike, value: BigNumberish],
    [bigint],
    "view"
  >;

  enforceTransferRestrictions: TypedContractMethod<
    [from: AddressLike, to: AddressLike, value: BigNumberish],
    [void],
    "view"
  >;

  freeze: TypedContractMethod<
    [addr: AddressLike, status: boolean],
    [void],
    "nonpayable"
  >;

  fundReleaseSchedule: TypedContractMethod<
    [
      to: AddressLike,
      amount: BigNumberish,
      commencementTimestamp: BigNumberish,
      scheduleId: BigNumberish,
      cancelableBy: AddressLike[]
    ],
    [boolean],
    "nonpayable"
  >;

  getAllowGroupTransferTime: TypedContractMethod<
    [from: BigNumberish, to: BigNumberish],
    [bigint],
    "view"
  >;

  getAllowTransferTime: TypedContractMethod<
    [from: AddressLike, to: AddressLike],
    [bigint],
    "view"
  >;

  getCurrentSnapshotId: TypedContractMethod<[], [bigint], "view">;

  getFrozenStatus: TypedContractMethod<[addr: AddressLike], [boolean], "view">;

  getMaxBalance: TypedContractMethod<[addr: AddressLike], [bigint], "view">;

  getTransferGroup: TypedContractMethod<[addr: AddressLike], [bigint], "view">;

  grantRole: TypedContractMethod<
    [addr: AddressLike, role: BigNumberish],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [addr: AddressLike, role: BigNumberish],
    [boolean],
    "view"
  >;

  increaseAllowance: TypedContractMethod<
    [spender: AddressLike, addedValue: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  isPaused: TypedContractMethod<[], [boolean], "view">;

  lockedAmountOf: TypedContractMethod<[who: AddressLike], [bigint], "view">;

  lockedAmountOfTimelock: TypedContractMethod<
    [who: AddressLike, timelockIndex: BigNumberish],
    [bigint],
    "view"
  >;

  maxReleaseDelay: TypedContractMethod<[], [bigint], "view">;

  maxTotalSupply: TypedContractMethod<[], [bigint], "view">;

  messageForTransferRestriction: TypedContractMethod<
    [restrictionCode: BigNumberish],
    [string],
    "view"
  >;

  minTimelockAmount: TypedContractMethod<[], [bigint], "view">;

  mint: TypedContractMethod<
    [to: AddressLike, value: BigNumberish],
    [void],
    "nonpayable"
  >;

  name: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  releaseSchedules: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint, bigint] & {
        releaseCount: bigint;
        delayUntilFirstReleaseInSeconds: bigint;
        initialReleasePortionInBips: bigint;
        periodBetweenReleasesInSeconds: bigint;
      }
    ],
    "view"
  >;

  revokeRole: TypedContractMethod<
    [addr: AddressLike, role: BigNumberish],
    [void],
    "nonpayable"
  >;

  safeApprove: TypedContractMethod<
    [spender: AddressLike, value: BigNumberish],
    [void],
    "nonpayable"
  >;

  scheduleCount: TypedContractMethod<[], [bigint], "view">;

  setAddressPermissions: TypedContractMethod<
    [
      addr: AddressLike,
      groupID: BigNumberish,
      lockedBalanceUntil: BigNumberish,
      maxBalance: BigNumberish,
      status: boolean
    ],
    [void],
    "nonpayable"
  >;

  setAllowGroupTransfer: TypedContractMethod<
    [from: BigNumberish, to: BigNumberish, lockedUntil: BigNumberish],
    [void],
    "nonpayable"
  >;

  setMaxBalance: TypedContractMethod<
    [addr: AddressLike, updatedValue: BigNumberish],
    [void],
    "nonpayable"
  >;

  setTransferGroup: TypedContractMethod<
    [addr: AddressLike, groupID: BigNumberish],
    [void],
    "nonpayable"
  >;

  snapshot: TypedContractMethod<[], [bigint], "nonpayable">;

  symbol: TypedContractMethod<[], [string], "view">;

  timelockBalanceOf: TypedContractMethod<[who: AddressLike], [bigint], "view">;

  timelockCountOf: TypedContractMethod<[who: AddressLike], [bigint], "view">;

  timelockOf: TypedContractMethod<
    [who: AddressLike, index: BigNumberish],
    [RestrictedLockupToken.TimelockStructOutput],
    "view"
  >;

  timelocks: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [
      [bigint, bigint, bigint, bigint] & {
        scheduleId: bigint;
        commencementTimestamp: bigint;
        tokensTransferred: bigint;
        totalAmount: bigint;
      }
    ],
    "view"
  >;

  tokensBalanceOf: TypedContractMethod<[who: AddressLike], [bigint], "view">;

  totalSupply: TypedContractMethod<[], [bigint], "view">;

  totalSupplyAt: TypedContractMethod<
    [snapshotId: BigNumberish],
    [bigint],
    "view"
  >;

  totalUnlockedToDateOfTimelock: TypedContractMethod<
    [who: AddressLike, timelockIndex: BigNumberish],
    [bigint],
    "view"
  >;

  transfer: TypedContractMethod<
    [recipient: AddressLike, amount: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  transferFrom: TypedContractMethod<
    [sender: AddressLike, recipient: AddressLike, amount: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  transferRules: TypedContractMethod<[], [string], "view">;

  transferTimelock: TypedContractMethod<
    [to: AddressLike, value: BigNumberish, timelockId: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  unlockedAmountOf: TypedContractMethod<[who: AddressLike], [bigint], "view">;

  unlockedAmountOfTimelock: TypedContractMethod<
    [who: AddressLike, timelockIndex: BigNumberish],
    [bigint],
    "view"
  >;

  unlockedBalanceOf: TypedContractMethod<[who: AddressLike], [bigint], "view">;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  upgradeTransferRules: TypedContractMethod<
    [newTransferRules: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "_decimals"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "allowance"
  ): TypedContractMethod<
    [owner: AddressLike, spender: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "approve"
  ): TypedContractMethod<
    [spender: AddressLike, amount: BigNumberish],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "balanceOf"
  ): TypedContractMethod<[who: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "balanceOfAt"
  ): TypedContractMethod<
    [account: AddressLike, snapshotId: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "balanceOfTimelock"
  ): TypedContractMethod<
    [who: AddressLike, timelockIndex: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "batchFundReleaseSchedule"
  ): TypedContractMethod<
    [
      to: AddressLike[],
      amounts: BigNumberish[],
      commencementTimestamps: BigNumberish[],
      scheduleIds: BigNumberish[],
      cancelableBy: AddressLike[]
    ],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "burn"
  ): TypedContractMethod<
    [from: AddressLike, value: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "calculateUnlocked(uint256,uint256,uint256,(uint256,uint256,uint256,uint256))"
  ): TypedContractMethod<
    [
      commencedTimestamp: BigNumberish,
      currentTimestamp: BigNumberish,
      amount: BigNumberish,
      releaseSchedule: RestrictedLockupToken.ReleaseScheduleStruct
    ],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "calculateUnlocked(uint256,uint256,uint256,uint256,uint256,uint256,uint256)"
  ): TypedContractMethod<
    [
      commencedTimestamp: BigNumberish,
      currentTimestamp: BigNumberish,
      amount: BigNumberish,
      releaseCount: BigNumberish,
      delayUntilFirstReleaseInSeconds: BigNumberish,
      initialReleasePortionInBips: BigNumberish,
      periodBetweenReleasesInSeconds: BigNumberish
    ],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "calculateUnlocked(uint256,uint256,uint256,uint256)"
  ): TypedContractMethod<
    [
      commencedTimestamp: BigNumberish,
      currentTimestamp: BigNumberish,
      amount: BigNumberish,
      scheduleId: BigNumberish
    ],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "cancelTimelock"
  ): TypedContractMethod<
    [
      target: AddressLike,
      timelockIndex: BigNumberish,
      scheduleId: BigNumberish,
      commencementTimestamp: BigNumberish,
      totalAmount: BigNumberish,
      reclaimTokenTo: AddressLike
    ],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "contractAdminCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "createReleaseSchedule"
  ): TypedContractMethod<
    [
      releaseCount: BigNumberish,
      delayUntilFirstReleaseInSeconds: BigNumberish,
      initialReleasePortionInBips: BigNumberish,
      periodBetweenReleasesInSeconds: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "decimals"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "decreaseAllowance"
  ): TypedContractMethod<
    [spender: AddressLike, subtractedValue: BigNumberish],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "detectTransferRestriction"
  ): TypedContractMethod<
    [from: AddressLike, to: AddressLike, value: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "enforceTransferRestrictions"
  ): TypedContractMethod<
    [from: AddressLike, to: AddressLike, value: BigNumberish],
    [void],
    "view"
  >;
  getFunction(
    nameOrSignature: "freeze"
  ): TypedContractMethod<
    [addr: AddressLike, status: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "fundReleaseSchedule"
  ): TypedContractMethod<
    [
      to: AddressLike,
      amount: BigNumberish,
      commencementTimestamp: BigNumberish,
      scheduleId: BigNumberish,
      cancelableBy: AddressLike[]
    ],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getAllowGroupTransferTime"
  ): TypedContractMethod<
    [from: BigNumberish, to: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAllowTransferTime"
  ): TypedContractMethod<
    [from: AddressLike, to: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getCurrentSnapshotId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getFrozenStatus"
  ): TypedContractMethod<[addr: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "getMaxBalance"
  ): TypedContractMethod<[addr: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getTransferGroup"
  ): TypedContractMethod<[addr: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [addr: AddressLike, role: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [addr: AddressLike, role: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "increaseAllowance"
  ): TypedContractMethod<
    [spender: AddressLike, addedValue: BigNumberish],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "isPaused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "lockedAmountOf"
  ): TypedContractMethod<[who: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "lockedAmountOfTimelock"
  ): TypedContractMethod<
    [who: AddressLike, timelockIndex: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "maxReleaseDelay"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "maxTotalSupply"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "messageForTransferRestriction"
  ): TypedContractMethod<[restrictionCode: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "minTimelockAmount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "mint"
  ): TypedContractMethod<
    [to: AddressLike, value: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "name"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "releaseSchedules"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint, bigint] & {
        releaseCount: bigint;
        delayUntilFirstReleaseInSeconds: bigint;
        initialReleasePortionInBips: bigint;
        periodBetweenReleasesInSeconds: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [addr: AddressLike, role: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "safeApprove"
  ): TypedContractMethod<
    [spender: AddressLike, value: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "scheduleCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "setAddressPermissions"
  ): TypedContractMethod<
    [
      addr: AddressLike,
      groupID: BigNumberish,
      lockedBalanceUntil: BigNumberish,
      maxBalance: BigNumberish,
      status: boolean
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setAllowGroupTransfer"
  ): TypedContractMethod<
    [from: BigNumberish, to: BigNumberish, lockedUntil: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setMaxBalance"
  ): TypedContractMethod<
    [addr: AddressLike, updatedValue: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setTransferGroup"
  ): TypedContractMethod<
    [addr: AddressLike, groupID: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "snapshot"
  ): TypedContractMethod<[], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "symbol"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "timelockBalanceOf"
  ): TypedContractMethod<[who: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "timelockCountOf"
  ): TypedContractMethod<[who: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "timelockOf"
  ): TypedContractMethod<
    [who: AddressLike, index: BigNumberish],
    [RestrictedLockupToken.TimelockStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "timelocks"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [
      [bigint, bigint, bigint, bigint] & {
        scheduleId: bigint;
        commencementTimestamp: bigint;
        tokensTransferred: bigint;
        totalAmount: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "tokensBalanceOf"
  ): TypedContractMethod<[who: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalSupply"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalSupplyAt"
  ): TypedContractMethod<[snapshotId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalUnlockedToDateOfTimelock"
  ): TypedContractMethod<
    [who: AddressLike, timelockIndex: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "transfer"
  ): TypedContractMethod<
    [recipient: AddressLike, amount: BigNumberish],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferFrom"
  ): TypedContractMethod<
    [sender: AddressLike, recipient: AddressLike, amount: BigNumberish],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferRules"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "transferTimelock"
  ): TypedContractMethod<
    [to: AddressLike, value: BigNumberish, timelockId: BigNumberish],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "unlockedAmountOf"
  ): TypedContractMethod<[who: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "unlockedAmountOfTimelock"
  ): TypedContractMethod<
    [who: AddressLike, timelockIndex: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "unlockedBalanceOf"
  ): TypedContractMethod<[who: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "upgradeTransferRules"
  ): TypedContractMethod<[newTransferRules: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "AddressFrozen"
  ): TypedContractEvent<
    AddressFrozenEvent.InputTuple,
    AddressFrozenEvent.OutputTuple,
    AddressFrozenEvent.OutputObject
  >;
  getEvent(
    key: "AddressMaxBalance"
  ): TypedContractEvent<
    AddressMaxBalanceEvent.InputTuple,
    AddressMaxBalanceEvent.OutputTuple,
    AddressMaxBalanceEvent.OutputObject
  >;
  getEvent(
    key: "AddressTransferGroup"
  ): TypedContractEvent<
    AddressTransferGroupEvent.InputTuple,
    AddressTransferGroupEvent.OutputTuple,
    AddressTransferGroupEvent.OutputObject
  >;
  getEvent(
    key: "AllowGroupTransfer"
  ): TypedContractEvent<
    AllowGroupTransferEvent.InputTuple,
    AllowGroupTransferEvent.OutputTuple,
    AllowGroupTransferEvent.OutputObject
  >;
  getEvent(
    key: "Approval"
  ): TypedContractEvent<
    ApprovalEvent.InputTuple,
    ApprovalEvent.OutputTuple,
    ApprovalEvent.OutputObject
  >;
  getEvent(
    key: "Pause"
  ): TypedContractEvent<
    PauseEvent.InputTuple,
    PauseEvent.OutputTuple,
    PauseEvent.OutputObject
  >;
  getEvent(
    key: "RoleChange"
  ): TypedContractEvent<
    RoleChangeEvent.InputTuple,
    RoleChangeEvent.OutputTuple,
    RoleChangeEvent.OutputObject
  >;
  getEvent(
    key: "ScheduleCreated"
  ): TypedContractEvent<
    ScheduleCreatedEvent.InputTuple,
    ScheduleCreatedEvent.OutputTuple,
    ScheduleCreatedEvent.OutputObject
  >;
  getEvent(
    key: "ScheduleFunded"
  ): TypedContractEvent<
    ScheduleFundedEvent.InputTuple,
    ScheduleFundedEvent.OutputTuple,
    ScheduleFundedEvent.OutputObject
  >;
  getEvent(
    key: "Snapshot"
  ): TypedContractEvent<
    SnapshotEvent.InputTuple,
    SnapshotEvent.OutputTuple,
    SnapshotEvent.OutputObject
  >;
  getEvent(
    key: "TimelockCanceled"
  ): TypedContractEvent<
    TimelockCanceledEvent.InputTuple,
    TimelockCanceledEvent.OutputTuple,
    TimelockCanceledEvent.OutputObject
  >;
  getEvent(
    key: "Transfer"
  ): TypedContractEvent<
    TransferEvent.InputTuple,
    TransferEvent.OutputTuple,
    TransferEvent.OutputObject
  >;
  getEvent(
    key: "Upgrade"
  ): TypedContractEvent<
    UpgradeEvent.InputTuple,
    UpgradeEvent.OutputTuple,
    UpgradeEvent.OutputObject
  >;

  filters: {
    "AddressFrozen(address,address,bool)": TypedContractEvent<
      AddressFrozenEvent.InputTuple,
      AddressFrozenEvent.OutputTuple,
      AddressFrozenEvent.OutputObject
    >;
    AddressFrozen: TypedContractEvent<
      AddressFrozenEvent.InputTuple,
      AddressFrozenEvent.OutputTuple,
      AddressFrozenEvent.OutputObject
    >;

    "AddressMaxBalance(address,address,uint256)": TypedContractEvent<
      AddressMaxBalanceEvent.InputTuple,
      AddressMaxBalanceEvent.OutputTuple,
      AddressMaxBalanceEvent.OutputObject
    >;
    AddressMaxBalance: TypedContractEvent<
      AddressMaxBalanceEvent.InputTuple,
      AddressMaxBalanceEvent.OutputTuple,
      AddressMaxBalanceEvent.OutputObject
    >;

    "AddressTransferGroup(address,address,uint256)": TypedContractEvent<
      AddressTransferGroupEvent.InputTuple,
      AddressTransferGroupEvent.OutputTuple,
      AddressTransferGroupEvent.OutputObject
    >;
    AddressTransferGroup: TypedContractEvent<
      AddressTransferGroupEvent.InputTuple,
      AddressTransferGroupEvent.OutputTuple,
      AddressTransferGroupEvent.OutputObject
    >;

    "AllowGroupTransfer(address,uint256,uint256,uint256)": TypedContractEvent<
      AllowGroupTransferEvent.InputTuple,
      AllowGroupTransferEvent.OutputTuple,
      AllowGroupTransferEvent.OutputObject
    >;
    AllowGroupTransfer: TypedContractEvent<
      AllowGroupTransferEvent.InputTuple,
      AllowGroupTransferEvent.OutputTuple,
      AllowGroupTransferEvent.OutputObject
    >;

    "Approval(address,address,uint256)": TypedContractEvent<
      ApprovalEvent.InputTuple,
      ApprovalEvent.OutputTuple,
      ApprovalEvent.OutputObject
    >;
    Approval: TypedContractEvent<
      ApprovalEvent.InputTuple,
      ApprovalEvent.OutputTuple,
      ApprovalEvent.OutputObject
    >;

    "Pause(address,bool)": TypedContractEvent<
      PauseEvent.InputTuple,
      PauseEvent.OutputTuple,
      PauseEvent.OutputObject
    >;
    Pause: TypedContractEvent<
      PauseEvent.InputTuple,
      PauseEvent.OutputTuple,
      PauseEvent.OutputObject
    >;

    "RoleChange(address,address,uint8,bool)": TypedContractEvent<
      RoleChangeEvent.InputTuple,
      RoleChangeEvent.OutputTuple,
      RoleChangeEvent.OutputObject
    >;
    RoleChange: TypedContractEvent<
      RoleChangeEvent.InputTuple,
      RoleChangeEvent.OutputTuple,
      RoleChangeEvent.OutputObject
    >;

    "ScheduleCreated(address,uint256)": TypedContractEvent<
      ScheduleCreatedEvent.InputTuple,
      ScheduleCreatedEvent.OutputTuple,
      ScheduleCreatedEvent.OutputObject
    >;
    ScheduleCreated: TypedContractEvent<
      ScheduleCreatedEvent.InputTuple,
      ScheduleCreatedEvent.OutputTuple,
      ScheduleCreatedEvent.OutputObject
    >;

    "ScheduleFunded(address,address,uint256,uint256,uint256,uint256,address[])": TypedContractEvent<
      ScheduleFundedEvent.InputTuple,
      ScheduleFundedEvent.OutputTuple,
      ScheduleFundedEvent.OutputObject
    >;
    ScheduleFunded: TypedContractEvent<
      ScheduleFundedEvent.InputTuple,
      ScheduleFundedEvent.OutputTuple,
      ScheduleFundedEvent.OutputObject
    >;

    "Snapshot(uint256)": TypedContractEvent<
      SnapshotEvent.InputTuple,
      SnapshotEvent.OutputTuple,
      SnapshotEvent.OutputObject
    >;
    Snapshot: TypedContractEvent<
      SnapshotEvent.InputTuple,
      SnapshotEvent.OutputTuple,
      SnapshotEvent.OutputObject
    >;

    "TimelockCanceled(address,address,uint256,address,uint256,uint256)": TypedContractEvent<
      TimelockCanceledEvent.InputTuple,
      TimelockCanceledEvent.OutputTuple,
      TimelockCanceledEvent.OutputObject
    >;
    TimelockCanceled: TypedContractEvent<
      TimelockCanceledEvent.InputTuple,
      TimelockCanceledEvent.OutputTuple,
      TimelockCanceledEvent.OutputObject
    >;

    "Transfer(address,address,uint256)": TypedContractEvent<
      TransferEvent.InputTuple,
      TransferEvent.OutputTuple,
      TransferEvent.OutputObject
    >;
    Transfer: TypedContractEvent<
      TransferEvent.InputTuple,
      TransferEvent.OutputTuple,
      TransferEvent.OutputObject
    >;

    "Upgrade(address,address,address)": TypedContractEvent<
      UpgradeEvent.InputTuple,
      UpgradeEvent.OutputTuple,
      UpgradeEvent.OutputObject
    >;
    Upgrade: TypedContractEvent<
      UpgradeEvent.InputTuple,
      UpgradeEvent.OutputTuple,
      UpgradeEvent.OutputObject
    >;
  };
}
