/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace SecurityTokenFactory {
  export type SecurityTokenStruct = {
    tokenAddress: AddressLike;
    transferRulesAddress: AddressLike;
    creator: AddressLike;
    name: string;
    symbol: string;
    decimals: BigNumberish;
    totalSupply: BigNumberish;
    maxTotalSupply: BigNumberish;
    documentHash: BytesLike;
    documentType: string;
    originalValue: BigNumberish;
    createdAt: BigNumberish;
  };

  export type SecurityTokenStructOutput = [
    tokenAddress: string,
    transferRulesAddress: string,
    creator: string,
    name: string,
    symbol: string,
    decimals: bigint,
    totalSupply: bigint,
    maxTotalSupply: bigint,
    documentHash: string,
    documentType: string,
    originalValue: bigint,
    createdAt: bigint
  ] & {
    tokenAddress: string;
    transferRulesAddress: string;
    creator: string;
    name: string;
    symbol: string;
    decimals: bigint;
    totalSupply: bigint;
    maxTotalSupply: bigint;
    documentHash: string;
    documentType: string;
    originalValue: bigint;
    createdAt: bigint;
  };
}

export interface SecurityTokenFactoryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "createSecurityToken"
      | "getTokenAtIndex"
      | "getTokenDetails"
      | "getTotalTokens"
      | "getUserTokens"
      | "isFactoryToken"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "SecurityTokenCreated"): EventFragment;

  encodeFunctionData(
    functionFragment: "createSecurityToken",
    values: [
      string,
      string,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BytesLike,
      string,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getTokenAtIndex",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTokenDetails",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalTokens",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getUserTokens",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isFactoryToken",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "createSecurityToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTokenAtIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTokenDetails",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isFactoryToken",
    data: BytesLike
  ): Result;
}

export namespace SecurityTokenCreatedEvent {
  export type InputTuple = [
    creator: AddressLike,
    tokenAddress: AddressLike,
    transferRulesAddress: AddressLike,
    name: string,
    symbol: string,
    totalSupply: BigNumberish,
    maxTotalSupply: BigNumberish,
    documentHash: BytesLike,
    documentType: string,
    originalValue: BigNumberish
  ];
  export type OutputTuple = [
    creator: string,
    tokenAddress: string,
    transferRulesAddress: string,
    name: string,
    symbol: string,
    totalSupply: bigint,
    maxTotalSupply: bigint,
    documentHash: string,
    documentType: string,
    originalValue: bigint
  ];
  export interface OutputObject {
    creator: string;
    tokenAddress: string;
    transferRulesAddress: string;
    name: string;
    symbol: string;
    totalSupply: bigint;
    maxTotalSupply: bigint;
    documentHash: string;
    documentType: string;
    originalValue: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SecurityTokenFactory extends BaseContract {
  connect(runner?: ContractRunner | null): SecurityTokenFactory;
  waitForDeployment(): Promise<this>;

  interface: SecurityTokenFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  createSecurityToken: TypedContractMethod<
    [
      _name: string,
      _symbol: string,
      _decimals: BigNumberish,
      _totalSupply: BigNumberish,
      _maxTotalSupply: BigNumberish,
      _documentHash: BytesLike,
      _documentType: string,
      _originalValue: BigNumberish,
      _minTimelockAmount: BigNumberish,
      _maxReleaseDelay: BigNumberish
    ],
    [[string, string] & { tokenAddress: string; rulesAddress: string }],
    "nonpayable"
  >;

  getTokenAtIndex: TypedContractMethod<
    [index: BigNumberish],
    [SecurityTokenFactory.SecurityTokenStructOutput],
    "view"
  >;

  getTokenDetails: TypedContractMethod<
    [tokenAddress: AddressLike],
    [SecurityTokenFactory.SecurityTokenStructOutput],
    "view"
  >;

  getTotalTokens: TypedContractMethod<[], [bigint], "view">;

  getUserTokens: TypedContractMethod<[user: AddressLike], [string[]], "view">;

  isFactoryToken: TypedContractMethod<
    [tokenAddress: AddressLike],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "createSecurityToken"
  ): TypedContractMethod<
    [
      _name: string,
      _symbol: string,
      _decimals: BigNumberish,
      _totalSupply: BigNumberish,
      _maxTotalSupply: BigNumberish,
      _documentHash: BytesLike,
      _documentType: string,
      _originalValue: BigNumberish,
      _minTimelockAmount: BigNumberish,
      _maxReleaseDelay: BigNumberish
    ],
    [[string, string] & { tokenAddress: string; rulesAddress: string }],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getTokenAtIndex"
  ): TypedContractMethod<
    [index: BigNumberish],
    [SecurityTokenFactory.SecurityTokenStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTokenDetails"
  ): TypedContractMethod<
    [tokenAddress: AddressLike],
    [SecurityTokenFactory.SecurityTokenStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTotalTokens"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getUserTokens"
  ): TypedContractMethod<[user: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "isFactoryToken"
  ): TypedContractMethod<[tokenAddress: AddressLike], [boolean], "view">;

  getEvent(
    key: "SecurityTokenCreated"
  ): TypedContractEvent<
    SecurityTokenCreatedEvent.InputTuple,
    SecurityTokenCreatedEvent.OutputTuple,
    SecurityTokenCreatedEvent.OutputObject
  >;

  filters: {
    "SecurityTokenCreated(address,address,address,string,string,uint256,uint256,bytes32,string,uint256)": TypedContractEvent<
      SecurityTokenCreatedEvent.InputTuple,
      SecurityTokenCreatedEvent.OutputTuple,
      SecurityTokenCreatedEvent.OutputObject
    >;
    SecurityTokenCreated: TypedContractEvent<
      SecurityTokenCreatedEvent.InputTuple,
      SecurityTokenCreatedEvent.OutputTuple,
      SecurityTokenCreatedEvent.OutputObject
    >;
  };
}
