/**
 * Extract ABI and bytecode from compiled Hardhat artifacts for contract templates.
 *
 * Reads artifacts from artifacts/contracts/templates/, extracts the ABI and
 * deployable bytecode for each template contract, and writes them as TypeScript
 * modules to src/contracts/templates/abis/<id>.ts and
 * src/contracts/templates/bytecodes.ts.
 *
 * Usage: npx tsx scripts/extract-template-artifacts.ts
 */

import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'fs';
import { join, resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const ROOT = resolve(__dirname, '..');
const ARTIFACTS_BASE = join(ROOT, 'artifacts', 'contracts', 'templates');
const ABI_OUT = join(ROOT, 'src', 'contracts', 'templates', 'abis');
const BYTECODES_OUT = join(ROOT, 'src', 'contracts', 'templates', 'bytecodes.ts');

/** Maps template ID to artifact file location (relative to ARTIFACTS_BASE). */
const TEMPLATE_MAP: Record<string, { path: string; contractName: string }> = {
  'simple-token': {
    path: 'tokens/FixedToken.sol/FixedToken.json',
    contractName: 'FixedToken',
  },
  'voting-token': {
    path: 'tokens/VotingToken.sol/VotingToken.json',
    contractName: 'VotingToken',
  },
  'antibot-erc20': {
    path: 'tokens/AntiBotERC20.sol/AntiBotERC20.json',
    contractName: 'AntiBotERC20',
  },
  'buyback-baby-token': {
    path: 'tokens/buyback/BuybackBabyToken.sol/BuybackBabyToken.json',
    contractName: 'BuybackBabyToken',
  },
  'soulbound-nft': {
    path: 'nfts/SoulboundNFT.sol/SoulboundNFT.json',
    contractName: 'SoulboundNFT',
  },
  'simple-multi-nft': {
    path: 'nfts/SimpleERC1155.sol/SimpleERC1155.json',
    contractName: 'SimpleERC1155',
  },
  'simple-staking': {
    path: 'staking/SingleStaking.sol/SingleStaking.json',
    contractName: 'SingleStaking',
  },
  'token-staking': {
    path: 'staking/Staking.sol/Staking.json',
    contractName: 'Staking',
  },
  'nft-staking-rewards': {
    path: 'staking/NFTStakingPerToken.sol/NFTStakingPerToken.json',
    contractName: 'NFTStakingPerToken',
  },
  'linear-vesting': {
    path: 'staking/LinearVesting.sol/LinearVesting.json',
    contractName: 'LinearVesting',
  },
  'dutch-auction': {
    path: 'trading/DutchAuction.sol/DutchAuction.json',
    contractName: 'DutchAuction',
  },
  presale: {
    path: 'trading/Presale.sol/Presale.json',
    contractName: 'Presale',
  },
  'escrow-agent': {
    path: 'utility/EscrowWithAgent.sol/EscrowWithAgent.json',
    contractName: 'EscrowWithAgent',
  },
  'escrow-dual': {
    path: 'utility/Escrow.sol/Escrow.json',
    contractName: 'Escrow',
  },
  'royalty-splitter': {
    path: 'utility/PaymentSplitter.sol/PaymentSplitter.json',
    contractName: 'PaymentSplitter',
  },
  lottery: {
    path: 'utility/Lottery.sol/Lottery.json',
    contractName: 'Lottery',
  },
};

function main() {
  if (!existsSync(ABI_OUT)) {
    mkdirSync(ABI_OUT, { recursive: true });
  }

  const bytecodeEntries: string[] = [];
  const templateIds = Object.keys(TEMPLATE_MAP);
  let successCount = 0;

  for (const id of templateIds) {
    const { path: relPath, contractName } = TEMPLATE_MAP[id];
    const artifactPath = join(ARTIFACTS_BASE, relPath);

    if (!existsSync(artifactPath)) {
      console.error(`  SKIP ${id}: artifact not found at ${artifactPath}`);
      continue;
    }

    const artifact = JSON.parse(readFileSync(artifactPath, 'utf-8'));
    const abi = artifact.abi;
    const bytecode: string = artifact.bytecode;

    if (!abi || !bytecode || bytecode === '0x') {
      console.error(`  SKIP ${id}: missing ABI or bytecode`);
      continue;
    }

    // Write ABI file
    const abiContent = [
      `// Auto-generated by scripts/extract-template-artifacts.ts`,
      `// Contract: ${contractName}`,
      `// Template: ${id}`,
      ``,
      `export const ${contractName}ABI = ${JSON.stringify(abi, null, 2)} as const;`,
      ``,
    ].join('\n');

    writeFileSync(join(ABI_OUT, `${id}.ts`), abiContent);

    // Collect bytecode
    bytecodeEntries.push(`  '${id}': '${bytecode}',`);
    successCount++;
    console.log(`  OK   ${id} (${contractName}) - ABI: ${abi.length} entries, bytecode: ${bytecode.length} chars`);
  }

  // Write bytecodes file
  const bytecodesContent = [
    `// Auto-generated by scripts/extract-template-artifacts.ts`,
    `// Do not edit manually.`,
    ``,
    `export const TEMPLATE_BYTECODES: Record<string, string> = {`,
    ...bytecodeEntries,
    `};`,
    ``,
  ].join('\n');

  writeFileSync(BYTECODES_OUT, bytecodesContent);

  console.log(`\nExtracted ${successCount}/${templateIds.length} templates.`);
  console.log(`  ABIs:      ${ABI_OUT}/`);
  console.log(`  Bytecodes: ${BYTECODES_OUT}`);
}

main();
