/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  DeployContractOptions,
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "AccessControl",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.AccessControl__factory>;
    getContractFactory(
      name: "IAccessControl",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IAccessControl__factory>;
    getContractFactory(
      name: "ERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC20__factory>;
    getContractFactory(
      name: "ERC20Snapshot",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC20Snapshot__factory>;
    getContractFactory(
      name: "IERC20Metadata",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20Metadata__factory>;
    getContractFactory(
      name: "IERC20Permit",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20Permit__factory>;
    getContractFactory(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20__factory>;
    getContractFactory(
      name: "ERC165",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC165__factory>;
    getContractFactory(
      name: "IERC165",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC165__factory>;
    getContractFactory(
      name: "AssetBackedExchange",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.AssetBackedExchange__factory>;
    getContractFactory(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20__factory>;
    getContractFactory(
      name: "AssetExchange",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.AssetExchange__factory>;
    getContractFactory(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20__factory>;
    getContractFactory(
      name: "LiquidityPoolAMM",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.LiquidityPoolAMM__factory>;
    getContractFactory(
      name: "OrbitalFactory",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.OrbitalFactory__factory>;
    getContractFactory(
      name: "OrbitalMath",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.OrbitalMath__factory>;
    getContractFactory(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20__factory>;
    getContractFactory(
      name: "OrbitalPool",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.OrbitalPool__factory>;
    getContractFactory(
      name: "IERC20Router",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20Router__factory>;
    getContractFactory(
      name: "OrbitalRouter",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.OrbitalRouter__factory>;
    getContractFactory(
      name: "Dividends",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Dividends__factory>;
    getContractFactory(
      name: "EasyAccessControl",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.EasyAccessControl__factory>;
    getContractFactory(
      name: "IDividends",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IDividends__factory>;
    getContractFactory(
      name: "IERC1404",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC1404__factory>;
    getContractFactory(
      name: "IERC20Decimals",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20Decimals__factory>;
    getContractFactory(
      name: "IRestrictedSwap",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IRestrictedSwap__factory>;
    getContractFactory(
      name: "ITransferRules",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ITransferRules__factory>;
    getContractFactory(
      name: "RestrictedLockupToken",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.RestrictedLockupToken__factory>;
    getContractFactory(
      name: "RestrictedSwap",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.RestrictedSwap__factory>;
    getContractFactory(
      name: "SecurityTokenDeployer",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SecurityTokenDeployer__factory>;
    getContractFactory(
      name: "SecurityTokenFactory",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SecurityTokenFactory__factory>;
    getContractFactory(
      name: "TransferRules",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.TransferRules__factory>;
    getContractFactory(
      name: "WrappedAsset",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.WrappedAsset__factory>;
    getContractFactory(
      name: "WrappedAssetFactory",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.WrappedAssetFactory__factory>;

    getContractAt(
      name: "AccessControl",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.AccessControl>;
    getContractAt(
      name: "IAccessControl",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IAccessControl>;
    getContractAt(
      name: "ERC20",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC20>;
    getContractAt(
      name: "ERC20Snapshot",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC20Snapshot>;
    getContractAt(
      name: "IERC20Metadata",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20Metadata>;
    getContractAt(
      name: "IERC20Permit",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20Permit>;
    getContractAt(
      name: "IERC20",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20>;
    getContractAt(
      name: "ERC165",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC165>;
    getContractAt(
      name: "IERC165",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC165>;
    getContractAt(
      name: "AssetBackedExchange",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.AssetBackedExchange>;
    getContractAt(
      name: "IERC20",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20>;
    getContractAt(
      name: "AssetExchange",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.AssetExchange>;
    getContractAt(
      name: "IERC20",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20>;
    getContractAt(
      name: "LiquidityPoolAMM",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.LiquidityPoolAMM>;
    getContractAt(
      name: "OrbitalFactory",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.OrbitalFactory>;
    getContractAt(
      name: "OrbitalMath",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.OrbitalMath>;
    getContractAt(
      name: "IERC20",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20>;
    getContractAt(
      name: "OrbitalPool",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.OrbitalPool>;
    getContractAt(
      name: "IERC20Router",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20Router>;
    getContractAt(
      name: "OrbitalRouter",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.OrbitalRouter>;
    getContractAt(
      name: "Dividends",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Dividends>;
    getContractAt(
      name: "EasyAccessControl",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.EasyAccessControl>;
    getContractAt(
      name: "IDividends",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IDividends>;
    getContractAt(
      name: "IERC1404",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC1404>;
    getContractAt(
      name: "IERC20Decimals",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20Decimals>;
    getContractAt(
      name: "IRestrictedSwap",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IRestrictedSwap>;
    getContractAt(
      name: "ITransferRules",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ITransferRules>;
    getContractAt(
      name: "RestrictedLockupToken",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.RestrictedLockupToken>;
    getContractAt(
      name: "RestrictedSwap",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.RestrictedSwap>;
    getContractAt(
      name: "SecurityTokenDeployer",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.SecurityTokenDeployer>;
    getContractAt(
      name: "SecurityTokenFactory",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.SecurityTokenFactory>;
    getContractAt(
      name: "TransferRules",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.TransferRules>;
    getContractAt(
      name: "WrappedAsset",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.WrappedAsset>;
    getContractAt(
      name: "WrappedAssetFactory",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.WrappedAssetFactory>;

    deployContract(
      name: "AccessControl",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.AccessControl>;
    deployContract(
      name: "IAccessControl",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IAccessControl>;
    deployContract(
      name: "ERC20",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC20>;
    deployContract(
      name: "ERC20Snapshot",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC20Snapshot>;
    deployContract(
      name: "IERC20Metadata",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20Metadata>;
    deployContract(
      name: "IERC20Permit",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20Permit>;
    deployContract(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20>;
    deployContract(
      name: "ERC165",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC165>;
    deployContract(
      name: "IERC165",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC165>;
    deployContract(
      name: "AssetBackedExchange",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.AssetBackedExchange>;
    deployContract(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20>;
    deployContract(
      name: "AssetExchange",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.AssetExchange>;
    deployContract(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20>;
    deployContract(
      name: "LiquidityPoolAMM",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.LiquidityPoolAMM>;
    deployContract(
      name: "OrbitalFactory",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.OrbitalFactory>;
    deployContract(
      name: "OrbitalMath",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.OrbitalMath>;
    deployContract(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20>;
    deployContract(
      name: "OrbitalPool",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.OrbitalPool>;
    deployContract(
      name: "IERC20Router",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20Router>;
    deployContract(
      name: "OrbitalRouter",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.OrbitalRouter>;
    deployContract(
      name: "Dividends",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Dividends>;
    deployContract(
      name: "EasyAccessControl",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.EasyAccessControl>;
    deployContract(
      name: "IDividends",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IDividends>;
    deployContract(
      name: "IERC1404",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC1404>;
    deployContract(
      name: "IERC20Decimals",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20Decimals>;
    deployContract(
      name: "IRestrictedSwap",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IRestrictedSwap>;
    deployContract(
      name: "ITransferRules",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ITransferRules>;
    deployContract(
      name: "RestrictedLockupToken",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.RestrictedLockupToken>;
    deployContract(
      name: "RestrictedSwap",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.RestrictedSwap>;
    deployContract(
      name: "SecurityTokenDeployer",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SecurityTokenDeployer>;
    deployContract(
      name: "SecurityTokenFactory",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SecurityTokenFactory>;
    deployContract(
      name: "TransferRules",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TransferRules>;
    deployContract(
      name: "WrappedAsset",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.WrappedAsset>;
    deployContract(
      name: "WrappedAssetFactory",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.WrappedAssetFactory>;

    deployContract(
      name: "AccessControl",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.AccessControl>;
    deployContract(
      name: "IAccessControl",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IAccessControl>;
    deployContract(
      name: "ERC20",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC20>;
    deployContract(
      name: "ERC20Snapshot",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC20Snapshot>;
    deployContract(
      name: "IERC20Metadata",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20Metadata>;
    deployContract(
      name: "IERC20Permit",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20Permit>;
    deployContract(
      name: "IERC20",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20>;
    deployContract(
      name: "ERC165",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC165>;
    deployContract(
      name: "IERC165",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC165>;
    deployContract(
      name: "AssetBackedExchange",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.AssetBackedExchange>;
    deployContract(
      name: "IERC20",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20>;
    deployContract(
      name: "AssetExchange",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.AssetExchange>;
    deployContract(
      name: "IERC20",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20>;
    deployContract(
      name: "LiquidityPoolAMM",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.LiquidityPoolAMM>;
    deployContract(
      name: "OrbitalFactory",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.OrbitalFactory>;
    deployContract(
      name: "OrbitalMath",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.OrbitalMath>;
    deployContract(
      name: "IERC20",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20>;
    deployContract(
      name: "OrbitalPool",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.OrbitalPool>;
    deployContract(
      name: "IERC20Router",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20Router>;
    deployContract(
      name: "OrbitalRouter",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.OrbitalRouter>;
    deployContract(
      name: "Dividends",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Dividends>;
    deployContract(
      name: "EasyAccessControl",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.EasyAccessControl>;
    deployContract(
      name: "IDividends",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IDividends>;
    deployContract(
      name: "IERC1404",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC1404>;
    deployContract(
      name: "IERC20Decimals",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20Decimals>;
    deployContract(
      name: "IRestrictedSwap",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IRestrictedSwap>;
    deployContract(
      name: "ITransferRules",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ITransferRules>;
    deployContract(
      name: "RestrictedLockupToken",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.RestrictedLockupToken>;
    deployContract(
      name: "RestrictedSwap",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.RestrictedSwap>;
    deployContract(
      name: "SecurityTokenDeployer",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SecurityTokenDeployer>;
    deployContract(
      name: "SecurityTokenFactory",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SecurityTokenFactory>;
    deployContract(
      name: "TransferRules",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TransferRules>;
    deployContract(
      name: "WrappedAsset",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.WrappedAsset>;
    deployContract(
      name: "WrappedAssetFactory",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.WrappedAssetFactory>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
